import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { createDatabase } from '../src/database.mjs';
import { createLecturerService } from '../src/lecturer-service.mjs';
import { Roles } from '../src/roles.mjs';

function fixture(){const db=createDatabase(':memory:');const now=new Date().toISOString();const collegeA=randomUUID(),collegeB=randomUUID(),lecturerA=randomUUID(),lecturerB=randomUUID(),classA=randomUUID(),classB=randomUUID();const college=db.prepare('INSERT INTO colleges (id,name,status,created_at,updated_at) VALUES (?,?\x2c\'ACTIVE\',?,?)');college.run(collegeA,'College A',now,now);college.run(collegeB,'College B',now,now);const user=db.prepare(`INSERT INTO users (id,name,login_identifier,password_hash,role,college_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,'ACTIVE',?,?)`);user.run(lecturerA,'Lecturer A','a@test','hash',Roles.LECTURER,collegeA,now,now);user.run(lecturerB,'Lecturer B','b@test','hash',Roles.LECTURER,collegeB,now,now);const students=[0,1].map(i=>{const id=randomUUID();user.run(id,`Student ${i+1}`,`s${i}@test`,'hash',Roles.STUDENT,collegeA,now,now);return id;});const cls=db.prepare(`INSERT INTO lecturer_classes (id,college_id,lecturer_id,subject_code,subject_name,batch_name,semester,schedule_text,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'ACTIVE',?,?)`);cls.run(classA,collegeA,lecturerA,'CS1','Algorithms','A','Semester 1','Monday',now,now);cls.run(classB,collegeB,lecturerB,'CS2','Networks','B','Semester 1','Tuesday',now,now);const enroll=db.prepare('INSERT INTO class_enrollments (class_id,student_id,roll_number,created_at) VALUES (?,?,?,?)');students.forEach((id,i)=>enroll.run(classA,id,`A${i+1}`,now));const sessionA={user:{id:lecturerA,role:Roles.LECTURER,college:{id:collegeA}}};return{db,service:createLecturerService(db),sessionA,classA,classB,students};}

test('lecturer sees only assigned classes and cross-tenant IDs are rejected',()=>{const x=fixture();assert.deepEqual(x.service.listClasses(x.sessionA).map(c=>c.id),[x.classA]);assert.throws(()=>x.service.classDetails(x.sessionA,x.classB),{code:'CLASS_NOT_FOUND'});x.db.close();});
test('class roster and enrolled student details load',()=>{const x=fixture();assert.equal(x.service.roster(x.sessionA,x.classA).length,2);assert.equal(x.service.student(x.sessionA,x.classA,x.students[0]).rollNumber,'A1');assert.throws(()=>x.service.student(x.sessionA,x.classA,randomUUID()),{code:'STUDENT_NOT_FOUND'});x.db.close();});
test('manual attendance submits once and appears in history',()=>{const x=fixture();const draft=x.service.startSession(x.sessionA,x.classA,{method:'MANUAL',scheduledAt:new Date().toISOString()});const records=x.students.map((studentId,i)=>({studentId,status:i?'ABSENT':'PRESENT'}));const complete=x.service.submit(x.sessionA,draft.id,{records});assert.equal(complete.status,'COMPLETED');assert.equal(complete.records[x.students[0]],'PRESENT');assert.throws(()=>x.service.submit(x.sessionA,draft.id,{records}),{code:'SESSION_ALREADY_SUBMITTED'});assert.equal(x.service.history(x.sessionA)[0].present,1);x.db.close();});
test('incomplete attendance fails and completed attendance can be corrected',()=>{const x=fixture();const draft=x.service.startSession(x.sessionA,x.classA,{method:'MANUAL'});assert.throws(()=>x.service.submit(x.sessionA,draft.id,{records:[{studentId:x.students[0],status:'PRESENT'}]}),{code:'INCOMPLETE_ATTENDANCE'});const records=x.students.map(studentId=>({studentId,status:'PRESENT'}));x.service.submit(x.sessionA,draft.id,{records});records[1].status='ABSENT';const corrected=x.service.submit(x.sessionA,draft.id,{records,note:'Correction'},{correction:true});assert.ok(corrected.correctedAt);assert.equal(corrected.records[x.students[1]],'ABSENT');x.db.close();});
