import assert from 'node:assert/strict';
import http from 'node:http';
import test from 'node:test';
import { createDatabase } from '../src/database.mjs';
import { createHttpApp } from '../src/http-app.mjs';

const config={nodeEnv:'development',sessionSecret:'onboarding-test-secret-more-than-thirty-two-chars',sessionTtlSeconds:3600,corsOrigin:'http://localhost:8083',paymentWebhookSecret:'payment-test-secret',invitationTtlSeconds:3600,otpTtlSeconds:600,onboardingBaseUrl:'http://localhost:8083/activate',exposeDevelopmentSecrets:true};
async function request(base,path,init={}){const response=await fetch(`${base}${path}`,{...init,headers:{'content-type':'application/json',...init.headers}});return{response,payload:await response.json()};}
test('paid college provisions idempotently and activates one real College Admin membership',async()=>{const db=createDatabase(':memory:');const sent=[];const server=http.createServer(createHttpApp({db,config,emailTransport:{send:async(message)=>sent.push(message)}}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;const input={paymentEventId:'pay-1',applicationReference:'APP-1',collegeName:'North College',legalName:'North College Trust',adminEmail:'admin@north.test',adminName:'Nora Admin'};const provision=await request(base,'/api/provisioning/payment-confirmed',{method:'POST',headers:{'x-rollcall-payment-secret':config.paymentWebhookSecret},body:JSON.stringify(input)});assert.equal(provision.response.status,201);assert.equal(provision.payload.data.workspace.state,'READY_FOR_ADMIN');assert.equal(sent.length,1);const again=await request(base,'/api/provisioning/payment-confirmed',{method:'POST',headers:{'x-rollcall-payment-secret':config.paymentWebhookSecret},body:JSON.stringify(input)});assert.equal(again.payload.data.idempotent,true);assert.equal(db.prepare('SELECT COUNT(*) value FROM workspaces').get().value,1);const token=provision.payload.data.developmentActivationUrl.split('/').at(-1);let result=await request(base,`/api/onboarding/invitations/${token}`);assert.equal(result.payload.data.email,'admin@north.test');await request(base,`/api/onboarding/invitations/${token}/confirm-college`,{method:'POST',body:'{}'});await request(base,`/api/onboarding/invitations/${token}/admin-details`,{method:'POST',body:JSON.stringify({name:'Nora Admin',phone:''})});result=await request(base,`/api/onboarding/invitations/${token}/otp/send`,{method:'POST',body:'{}'});const otp=result.payload.data.developmentOtp;assert.match(otp,/^\d{6}$/);result=await request(base,`/api/onboarding/invitations/${token}/otp/verify`,{method:'POST',body:JSON.stringify({code:otp})});assert.equal(result.payload.data.verified,true);result=await request(base,`/api/onboarding/invitations/${token}/activate`,{method:'POST',body:JSON.stringify({password:'StrongPassword!42',confirmPassword:'StrongPassword!42'})});assert.equal(result.response.status,201);assert.equal(result.payload.data.user.workspace.state,'ACTIVE');const authToken=result.payload.data.token;const setup=await request(base,'/api/admin/setup',{headers:{authorization:`Bearer ${authToken}`}});assert.equal(setup.response.status,200);assert.equal(setup.payload.data.completed,1);assert.equal(db.prepare("SELECT COUNT(*) value FROM workspace_memberships WHERE role='COLLEGE_ADMIN'").get().value,1);const reuse=await request(base,`/api/onboarding/invitations/${token}/activate`,{method:'POST',body:JSON.stringify({password:'StrongPassword!42',confirmPassword:'StrongPassword!42'})});assert.equal(reuse.response.status,409);await new Promise(resolve=>server.close(resolve));db.close();});

test('provisioning rejects an invalid payment secret',async()=>{const db=createDatabase(':memory:');const server=http.createServer(createHttpApp({db,config}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;const result=await request(base,'/api/provisioning/payment-confirmed',{method:'POST',headers:{'x-rollcall-payment-secret':'wrong'},body:JSON.stringify({})});assert.equal(result.response.status,403);await new Promise(resolve=>server.close(resolve));db.close();});
