import { useState } from 'react';
import { router, type Href, useLocalSearchParams } from 'expo-router';
import { Text, View } from 'react-native';
import { Badge, Button, Progress } from '@/design-system/components/core';
import { Confirmation } from '@/design-system/components/feedback';
import { StateView } from '@/design-system/components/states';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { ManagementRow, RelationshipSection } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function StudentManagementDetail() {
  const { colors } = useRollCallTheme(); const { studentId } = useLocalSearchParams<{ studentId: string }>(); const data = useHodManagement(); const [confirm, setConfirm] = useState(false); const student = data.students.find((item) => item.id === studentId);
  if (!student) return <HodShell activeKey="department" title="Student" back><PageContainer><StateView state="empty" title="Student not found" message="This student is not available in your department." /></PageContainer></HodShell>;
  const semester = data.semesters.find((item) => item.id === student.semesterId); const batch = data.batches.find((item) => item.id === student.batchId); const section = data.sections.find((item) => item.id === student.sectionId); const teacher = data.lecturers.find((item) => item.id === section?.classTeacherId);
  return <HodShell activeKey="department" title="Student details" subtitle={student.usn} back backFallback="/hod/management/students"><PageContainer width="detail"><View style={{ gap: spacing.md }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}><View style={{ flex: 1, gap: spacing.xs }}><Text accessibilityRole="header" style={[typography.largeTitle, { color: colors.textPrimary }]}>{student.name}</Text><Text style={[typography.body, { color: colors.textSecondary }]}>{student.email}</Text></View><Badge label={student.status} tone={student.status === 'Active' ? 'success' : 'neutral'} /></View><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }}><Button label="Edit details" variant="secondary" onPress={() => router.push(`/hod/management/students/${student.id}/edit` as Href)} /><Button label="Academic placement" onPress={() => router.push(`/hod/management/students/${student.id}/placement` as Href)} /><Button label={student.status === 'Active' ? 'Deactivate' : 'Activate'} variant="secondary" onPress={() => setConfirm(true)} /><Button label="Open attendance" variant="text" onPress={() => router.push('/hod/history' as Href)} /></View></View><RelationshipSection title="Academic placement"><ManagementRow title={data.department.name} detail={`${semester?.name} · ${batch?.name} · ${section?.name}`} meta={`Class Teacher: ${teacher?.name ?? 'Not assigned'}`} /></RelationshipSection><RelationshipSection title="Attendance summary"><Progress value={student.attendance} label="Overall attendance" /><Text style={[typography.bodySmall, { color: colors.textSecondary, paddingTop: spacing.md }]}>{student.attendance < 75 ? 'Needs attention. The student is below the current attendance threshold.' : 'Attendance is at or above the current threshold.'}</Text></RelationshipSection><RelationshipSection title="Account"><ManagementRow title="Student identity" detail={student.usn} meta={`Department: ${data.department.code}`} /><ManagementRow title="Account status" detail={student.status === 'Active' ? 'Can access RollCall' : 'Access is currently disabled'} /></RelationshipSection><Confirmation visible={confirm} title={`${student.status === 'Active' ? 'Deactivate' : 'Activate'} student?`} message={`${student.name}'s identity and academic history will be preserved.`} confirmLabel={student.status === 'Active' ? 'Deactivate' : 'Activate'} destructive={student.status === 'Active'} onDismiss={() => setConfirm(false)} onConfirm={() => { data.toggleStudent(student.id); setConfirm(false); }} /></PageContainer></HodShell>;
}
