import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Button } from '@/design-system/components/core';
import { AlertBanner, Confirmation } from '@/design-system/components/feedback';
import { StateView } from '@/design-system/components/states';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { ManagementRow, OptionPicker, RelationshipSection } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function StudentPlacement() {
  const { studentId } = useLocalSearchParams<{ studentId: string }>(); const data = useHodManagement(); const student = data.students.find((item) => item.id === studentId); const [semesterId, setSemester] = useState(student?.semesterId ?? ''); const [batchId, setBatch] = useState(student?.batchId ?? ''); const [sectionId, setSection] = useState(student?.sectionId ?? ''); const [confirm, setConfirm] = useState(false);
  if (!student) return <HodShell activeKey="department" title="Academic placement" back><PageContainer><StateView state="empty" title="Student not found" /></PageContainer></HodShell>;
  const currentSection = data.sections.find((item) => item.id === student.sectionId); const nextSection = data.sections.find((item) => item.id === sectionId); const changed = semesterId !== student.semesterId || batchId !== student.batchId || sectionId !== student.sectionId;
  return <HodShell activeKey="department" title="Academic placement" subtitle={student.name} back backFallback={`/hod/management/students/${student.id}`}><PageContainer width="compact" fixedActions={<Button label="Review placement" disabled={!changed || !sectionId} onPress={() => setConfirm(true)} />}><AlertBanner title="Identity is preserved" message="Moving this student changes academic placement only. It does not create another account." tone="info" /><RelationshipSection title="Current"><ManagementRow title={currentSection?.name ?? 'Unassigned'} detail={`${data.semesters.find((item) => item.id === student.semesterId)?.name} · ${data.batches.find((item) => item.id === student.batchId)?.name}`} /></RelationshipSection><OptionPicker label="Semester" value={semesterId} options={data.semesters.filter((item) => item.status === 'Active').map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => { setSemester(value); setBatch(''); setSection(''); }} /><OptionPicker label="Batch" value={batchId} disabled={!semesterId} options={data.batches.filter((item) => item.semesterId === semesterId).map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => { setBatch(value); setSection(''); }} /><OptionPicker label="Class / Section" value={sectionId} disabled={!batchId} options={data.sections.filter((item) => item.batchId === batchId).map((item) => ({ value: item.id, label: item.name }))} onChange={setSection} /><Confirmation visible={confirm} title="Move student?" message={`${student.name} will move from ${currentSection?.name ?? 'the current placement'} to ${nextSection?.name ?? 'the selected placement'}. Their identity and history remain unchanged.`} confirmLabel="Move student" onDismiss={() => setConfirm(false)} onConfirm={() => { data.updateStudentPlacement(student.id, { semesterId, batchId, sectionId }); setConfirm(false); router.back(); }} /></PageContainer></HodShell>;
}
