import { useMemo, useState } from 'react';
import { router, type Href, useLocalSearchParams } from 'expo-router';
import { StateView } from '@/design-system/components/states';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { FilterChips, ManagementHeader, ManagementRow, ManagementSearch, SummaryStrip } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function LecturerManagement() {
  const data = useHodManagement(); const params = useLocalSearchParams<{ filter?: string }>(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'active' | 'pending' | 'class-teacher'>(params.filter === 'pending' ? 'pending' : 'all');
  const people = useMemo(() => data.lecturers.filter((item) => item.id !== 'me' && `${item.name} ${item.employeeId} ${item.email}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || filter === 'active' && item.status === 'Active' || filter === 'pending' && item.status === 'Pending' || filter === 'class-teacher' && data.sections.some((section) => section.classTeacherId === item.id))), [data.lecturers, data.sections, filter, query]);
  return <HodShell activeKey="department" title="Lecturers" subtitle={`${data.lecturers.length - 1} department lecturers`} back backFallback="/hod/management"><PageContainer width="full"><ManagementHeader title="Department lecturers" description="Invite lecturers and understand their current teaching relationships." action="Add lecturer" onAction={() => router.push('/hod/management/lecturers/new' as Href)} /><SummaryStrip items={[{ value: data.lecturers.filter((item) => item.id !== 'me').length, label: 'Lecturers' }, { value: data.lecturers.filter((item) => item.id !== 'me' && item.status === 'Active').length, label: 'Active' }, { value: data.lecturers.filter((item) => item.status === 'Pending').length, label: 'Invited' }]} /><ManagementSearch value={query} onChangeText={setQuery} placeholder="Search name, employee ID, or email" /><FilterChips value={filter} onChange={setFilter} options={[{ value: 'all', label: 'All' }, { value: 'active', label: 'Active' }, { value: 'pending', label: 'Invitation pending' }, { value: 'class-teacher', label: 'Class Teachers' }]} />{people.length ? people.map((lecturer) => { const assigned = data.assignments.filter((item) => item.active && item.lecturerId === lecturer.id); const teacher = data.sections.filter((item) => item.classTeacherId === lecturer.id); return <ManagementRow key={lecturer.id} title={lecturer.name} detail={`${lecturer.employeeId} · ${lecturer.email}`} meta={`${assigned.length} teaching assignment${assigned.length === 1 ? '' : 's'} · ${teacher.length ? `Class Teacher: ${teacher.map((item) => item.name).join(', ')}` : 'Not a Class Teacher'}`} status={lecturer.status} onPress={() => router.push(`/hod/management/lecturers/${lecturer.id}` as Href)} />; }) : <StateView state="empty" title="No lecturers found" message={query ? 'Try another search or filter.' : 'No lecturers have been added yet.'} />}</PageContainer></HodShell>;
}
