import React, { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { router, type Href } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Badge, Button, IconButton } from '@/design-system/components/core';
import { radii, sizing, spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import type { AttendanceSessionState, ScheduleEntry } from './operations-provider';
import { useHodManagement } from './management-provider';

export function WorkspaceSwitch({ active }: { active: 'teaching' | 'department' }) { const { colors } = useRollCallTheme(); return <View accessibilityRole="tablist" accessibilityLabel="HOD workspace" style={{ alignSelf: 'flex-start', flexDirection: 'row', padding: spacing.xs, borderRadius: radii.md, backgroundColor: colors.surfaceSecondary }}><Pressable accessibilityRole="tab" accessibilityState={{ selected: active === 'teaching' }} onPress={() => router.navigate('/hod' as Href)} style={{ minHeight: sizing.touchTarget, justifyContent: 'center', paddingHorizontal: spacing.lg, borderRadius: radii.sm, backgroundColor: active === 'teaching' ? colors.surface : 'transparent' }}><Text style={[typography.label, { color: active === 'teaching' ? colors.primary : colors.textSecondary }]}>My Teaching</Text></Pressable><Pressable accessibilityRole="tab" accessibilityState={{ selected: active === 'department' }} onPress={() => router.navigate('/hod/management' as Href)} style={{ minHeight: sizing.touchTarget, justifyContent: 'center', paddingHorizontal: spacing.lg, borderRadius: radii.sm, backgroundColor: active === 'department' ? colors.surface : 'transparent' }}><Text style={[typography.label, { color: active === 'department' ? colors.primary : colors.textSecondary }]}>Department</Text></Pressable></View>; }

export function ScheduleRow({ entry, state, onPress }: { entry: ScheduleEntry; state?: AttendanceSessionState; onPress?: () => void }) { const { colors } = useRollCallTheme(); const data = useHodManagement(); const subject = data.subjects.find((item) => item.id === entry.subjectId); const section = data.sections.find((item) => item.id === entry.sectionId); const lecturer = data.lecturers.find((item) => item.id === entry.lecturerId); const tone = state === 'Conducted' ? 'success' : state === 'Not Conducted' ? 'neutral' : 'warning'; const content = <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.lg }}><View style={{ width: 76, gap: spacing.xxs }}><Text style={[typography.numeric, { color: colors.textPrimary }]}>{entry.startTime}</Text><Text style={[typography.caption, { color: colors.textMuted }]}>{entry.endTime}</Text></View><View style={{ flex: 1, gap: spacing.xs }}><Text style={[typography.subheading, { color: colors.textPrimary }]}>{subject?.name}</Text><Text style={[typography.bodySmall, { color: colors.textSecondary }]}>{section?.name} · {lecturer?.name}</Text><Text style={[typography.caption, { color: colors.textMuted }]}>{entry.room}</Text></View>{state ? <Badge label={state} tone={tone} /> : null}{onPress ? <Ionicons name="chevron-forward" size={sizing.iconSm} color={colors.textMuted} /> : null}</View>; return onPress ? <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => ({ minHeight: 84, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.borderSubtle, opacity: pressed ? .68 : 1 })}>{content}</Pressable> : <View style={{ minHeight: 84, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.borderSubtle }}>{content}</View>; }

export function AttentionRow({ title, detail, count, action, onPress }: { title: string; detail: string; count?: number; action?: string; onPress: () => void }) { const { colors } = useRollCallTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => ({ minHeight: 68, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.borderSubtle, flexDirection: 'row', alignItems: 'center', gap: spacing.md, opacity: pressed ? .68 : 1 })}><View style={{ flex: 1, gap: spacing.xs }}><Text style={[typography.label, { color: colors.textPrimary }]}>{count !== undefined ? `${count} ` : ''}{title}</Text><Text style={[typography.caption, { color: colors.textMuted }]}>{detail}</Text></View><Text style={[typography.label, { color: colors.primary }]}>{action ?? 'Review'}</Text></Pressable>; }

export function CopyIdentifier({ label, value }: { label: string; value: string }) { const { colors } = useRollCallTheme(); const [copied, setCopied] = useState(false); return <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}><Text selectable style={[typography.numeric, { color: colors.textSecondary }]}>{value}</Text><IconButton label={`Copy ${label}`} onPress={() => { void Clipboard.setStringAsync(value).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1800); }); }}><Ionicons name={copied ? 'checkmark' : 'copy-outline'} size={sizing.iconSm} color={copied ? colors.success : colors.primary} /></IconButton>{copied ? <Text accessibilityLiveRegion="polite" style={[typography.caption, { color: colors.success }]}>Copied</Text> : null}</View>; }

export function LastUpdated({ value }: { value: string }) { const { colors } = useRollCallTheme(); return <Text style={[typography.caption, { color: colors.textMuted }]}>Last updated {new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</Text>; }

export function BulkActionBar({ selected, total, onSelectAll, onClear, action, onAction }: { selected: number; total: number; onSelectAll: () => void; onClear: () => void; action: string; onAction: () => void }) { const { colors } = useRollCallTheme(); if (!selected) return null; return <View style={{ borderRadius: radii.md, padding: spacing.md, backgroundColor: colors.surfaceSecondary, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.sm }}><Text style={[typography.label, { color: colors.textPrimary, marginRight: 'auto' }]}>{selected} selected</Text><Button label={selected === total ? 'All visible selected' : 'Select all visible'} variant="text" disabled={selected === total} onPress={onSelectAll} /><Button label="Clear" variant="text" onPress={onClear} /><Button label={action} variant="secondary" onPress={onAction} /></View>; }
