import { router, type Href, useLocalSearchParams } from 'expo-router';
import { Text, View } from 'react-native';
import { Button } from '@/design-system/components/core';
import { StateView } from '@/design-system/components/states';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { ManagementRow, RelationshipSection, SummaryStrip } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function ClassSectionDetail() {
  const { colors } = useRollCallTheme(); const { sectionId } = useLocalSearchParams<{ sectionId: string }>(); const data = useHodManagement(); const section = data.sections.find((item) => item.id === sectionId);
  if (!section) return <HodShell activeKey="department" title="Class" back><PageContainer><StateView state="empty" title="Class not found" /></PageContainer></HodShell>;
  const semester = data.semesters.find((item) => item.id === section.semesterId); const batch = data.batches.find((item) => item.id === section.batchId); const teacher = data.lecturers.find((item) => item.id === section.classTeacherId); const assignments = data.assignments.filter((item) => item.sectionId === section.id && item.active); const students = data.students.filter((item) => item.sectionId === section.id);
  return <HodShell activeKey="department" title="Class details" subtitle={section.name} back backFallback="/hod/management/classes"><PageContainer width="detail"><View style={{ gap: spacing.xs }}><Text accessibilityRole="header" style={[typography.largeTitle, { color: colors.textPrimary }]}>{section.name}</Text><Text style={[typography.body, { color: colors.textSecondary }]}>{semester?.name} · {batch?.name} · {data.department.name}</Text></View><SummaryStrip items={[{ value: students.length, label: 'Students' }, { value: assignments.length, label: 'Subjects' }, { value: teacher ? 1 : 0, label: 'Class Teacher' }]} /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }}><Button label={teacher ? 'Change Class Teacher' : 'Assign Class Teacher'} onPress={() => router.push(`/hod/management/class-teachers?section=${section.id}` as Href)} /><Button label="Assign lecturer" variant="secondary" onPress={() => router.push(`/hod/management/assignments?section=${section.id}` as Href)} /></View><RelationshipSection title="Class Teacher"><ManagementRow title={teacher?.name ?? 'Not assigned'} detail={teacher ? `${teacher.employeeId} · Current responsibility` : 'Assign a lecturer or yourself'} status={teacher ? 'Assigned' : 'Unassigned'} onPress={() => router.push(`/hod/management/class-teachers?section=${section.id}` as Href)} /></RelationshipSection><RelationshipSection title="Subjects and lecturers">{assignments.length ? assignments.map((assignment) => { const subject = data.subjects.find((item) => item.id === assignment.subjectId); const lecturer = data.lecturers.find((item) => item.id === assignment.lecturerId); return <ManagementRow key={assignment.id} title={subject?.name ?? 'Subject'} detail={`${subject?.code} · ${lecturer?.name ?? 'Unassigned'}`} onPress={() => router.push(`/hod/management/subjects/${subject?.id}` as Href)} />; }) : <ManagementRow title="No subject coverage" detail="Assign a lecturer to a subject for this class." onPress={() => router.push(`/hod/management/assignments?section=${section.id}` as Href)} />}</RelationshipSection><RelationshipSection title="Students">{students.slice(0, 5).map((student) => <ManagementRow key={student.id} title={student.name} detail={`${student.usn} · ${student.attendance}% attendance`} onPress={() => router.push(`/hod/management/students/${student.id}` as Href)} />)}{students.length > 5 ? <ManagementRow title={`View all ${students.length} students`} detail="Open the department student list" onPress={() => router.push('/hod/management/students' as Href)} /> : null}</RelationshipSection></PageContainer></HodShell>;
}
