import { useMemo, useState } from 'react';
import { router, type Href } from 'expo-router';
import { StateView } from '@/design-system/components/states';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { FilterChips, ManagementHeader, ManagementRow, ManagementSearch, SummaryStrip } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';
import { useHodOperations } from '@/hod/operations-provider';

export default function ClassSectionManagement() {
  const data = useHodManagement(); const operations = useHodOperations(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'assigned' | 'unassigned'>('all'); const sections = useMemo(() => data.sections.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || filter === 'assigned' && item.classTeacherId || filter === 'unassigned' && !item.classTeacherId)).sort((a,b) => Number(b.id === operations.pinnedSectionId) - Number(a.id === operations.pinnedSectionId)), [data.sections, filter, operations.pinnedSectionId, query]);
  return <HodShell activeKey="department" title="Classes & sections" subtitle={`${data.sections.length} configured`} back backFallback="/hod/management"><PageContainer width="full"><ManagementHeader title="Classes & sections" description="Manage department sections, enrolment, and Class Teacher responsibility." action="Create class" onAction={() => router.push('/hod/management/classes/new' as Href)} /><SummaryStrip items={[{ value: data.sections.length, label: 'Classes' }, { value: data.sections.reduce((sum, item) => sum + item.studentCount, 0), label: 'Students' }, { value: data.sections.filter((item) => item.classTeacherId).length, label: 'Teachers assigned' }]} /><ManagementSearch value={query} onChangeText={setQuery} placeholder="Search class or section" /><FilterChips value={filter} onChange={setFilter} options={[{ value: 'all', label: 'All' }, { value: 'assigned', label: 'Class Teacher assigned' }, { value: 'unassigned', label: 'Unassigned' }]} />{sections.length ? sections.map((section) => { const semester = data.semesters.find((item) => item.id === section.semesterId); const batch = data.batches.find((item) => item.id === section.batchId); const teacher = data.lecturers.find((item) => item.id === section.classTeacherId); return <ManagementRow key={section.id} title={section.name} detail={`${semester?.name} · ${batch?.name} · ${section.studentCount} students`} meta={`Class Teacher: ${teacher?.name ?? 'Not assigned'}`} status={section.classTeacherId ? 'Assigned' : 'Unassigned'} onPress={() => router.push(`/hod/management/classes/${section.id}` as Href)} />; }) : <StateView state="empty" title="No classes found" message={query ? 'Try another search or filter.' : 'No classes have been configured.'} />}</PageContainer></HodShell>;
}
