import { useMemo, useState } from 'react';
import { router, type Href } from 'expo-router';
import { StateView } from '@/design-system/components/states';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { FilterChips, ManagementHeader, ManagementRow, ManagementSearch, SummaryStrip } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function SubjectsManagement() {
  const data = useHodManagement(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'assigned' | 'unassigned'>('all');
  const subjects = useMemo(() => data.subjects.filter((item) => { const assigned = data.assignments.some((assignment) => assignment.subjectId === item.id && assignment.active); return `${item.name} ${item.code}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || filter === 'assigned' && assigned || filter === 'unassigned' && !assigned); }), [data.assignments, data.subjects, filter, query]);
  return <HodShell activeKey="department" title="Subjects" subtitle={`${data.subjects.length} configured`} back backFallback="/hod/management"><PageContainer width="full"><ManagementHeader title="Department subjects" description="Subjects stay connected to academic year, semester, and batch." action="Add subject" onAction={() => router.push('/hod/management/subjects/new' as Href)} /><SummaryStrip items={[{ value: data.subjects.length, label: 'Subjects' }, { value: data.subjects.filter((item) => data.assignments.some((a) => a.subjectId === item.id && a.active)).length, label: 'Assigned' }, { value: data.subjects.filter((item) => !data.assignments.some((a) => a.subjectId === item.id && a.active)).length, label: 'Unassigned' }]} /><ManagementSearch value={query} onChangeText={setQuery} placeholder="Search subject name or code" /><FilterChips value={filter} onChange={setFilter} options={[{ value: 'all', label: 'All' }, { value: 'assigned', label: 'Assigned' }, { value: 'unassigned', label: 'Unassigned' }]} />{subjects.length ? subjects.map((subject) => { const assignment = data.assignments.find((item) => item.subjectId === subject.id && item.active); const lecturer = data.lecturers.find((item) => item.id === assignment?.lecturerId); const semester = data.semesters.find((item) => item.id === subject.semesterId); return <ManagementRow key={subject.id} title={subject.name} detail={`${subject.code} · ${semester?.name} · ${subject.credits} credits`} meta={lecturer ? `Lecturer: ${lecturer.name}` : 'Lecturer not assigned'} status={assignment ? 'Assigned' : 'Unassigned'} onPress={() => router.push(`/hod/management/subjects/${subject.id}` as Href)} />; }) : <StateView state="empty" title="No subjects found" message={query ? 'Try another search or filter.' : 'No subjects have been configured for this academic period.'} />}</PageContainer></HodShell>;
}
