import { router, type Href } from 'expo-router';
import { Text, View } from 'react-native';
import { Button, Progress } from '@/design-system/components/core';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { ManagementHeader, ManagementRow, RelationshipSection, SummaryStrip } from '@/hod/management-components';
import { LastUpdated, ScheduleRow } from '@/hod/operations-components';
import { useHodManagement } from '@/hod/management-provider';
import { useHodOperations } from '@/hod/operations-provider';

export default function DepartmentAttendance() {
  const { colors } = useRollCallTheme(); const data = useHodManagement(); const operations = useHodOperations(); const conducted = operations.sessions.filter((item) => item.state === 'Conducted'); const pending = operations.sessions.filter((item) => item.state === 'Pending'); const notConducted = operations.sessions.filter((item) => item.state === 'Not Conducted'); const present = conducted.reduce((sum, item) => sum + item.present, 0); const total = conducted.reduce((sum, item) => sum + item.total, 0); const overall = total ? Math.round(present / total * 100) : 0; const latest = operations.sessions.reduce((value, item) => item.updatedAt > value ? item.updatedAt : value, operations.sessions[0]?.updatedAt ?? new Date().toISOString());
  return <HodShell activeKey="department" title="Department attendance" subtitle="Operational monitoring" back backFallback="/hod/management"><PageContainer width="full"><ManagementHeader title="Attendance overview" description="Completion, participation, and attention items across your department." /><SummaryStrip items={[{ value: `${overall}%`, label: 'Department attendance' }, { value: conducted.length, label: 'Conducted' }, { value: pending.length, label: 'Pending' }, { value: notConducted.length, label: 'Not conducted' }]} /><Progress value={overall} label="Conducted-session attendance" /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }}><Button label="Low attendance" onPress={() => router.push('/hod/management/attendance/low' as Href)} /><Button label="Attendance issues" variant="secondary" onPress={() => router.push('/hod/management/issues' as Href)} /><Button label="Lecturer monitoring" variant="text" onPress={() => router.push('/hod/management/monitoring' as Href)} /></View><RelationshipSection title="Today's class completion">{operations.schedules.filter((schedule) => operations.sessions.some((session) => session.scheduleId === schedule.id)).map((entry) => <ScheduleRow key={entry.id} entry={entry} state={operations.sessions.find((item) => item.scheduleId === entry.id)?.state} onPress={() => router.push(`/hod/management/schedule/${entry.id}` as Href)} />)}</RelationshipSection><RelationshipSection title="Academic context"><ManagementRow title="Semester 7" detail={`${data.students.filter((item) => item.semesterId === 'sem-7').length} students`} meta={`${Math.round(data.students.filter((item) => item.semesterId === 'sem-7').reduce((sum,item) => sum + item.attendance, 0) / Math.max(1,data.students.filter((item) => item.semesterId === 'sem-7').length))}% average attendance`} /><ManagementRow title="Batch 2024" detail="CSE 2024 A" meta={`${data.students.filter((item) => item.attendance < 75).length} students need attention`} onPress={() => router.push('/hod/management/attendance/low' as Href)} /></RelationshipSection><Text style={[typography.caption, { color: colors.textMuted }]}>Absent means a student missed a conducted session. Not conducted means the class did not happen. Pending means the attendance process is incomplete.</Text><LastUpdated value={latest} /></PageContainer></HodShell>;
}
