import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, Text, View } from 'react-native';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuth } from '@/auth/auth-provider';
import { onboardingClient, type Invitation } from '@/auth/onboarding-client';
import { AuthApiError } from '@/auth/types';
import { Button, Card, Progress } from '@/design-system/components/core';
import { AlertBanner } from '@/design-system/components/feedback';
import { TextField } from '@/design-system/components/forms';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';

type Step='college'|'details'|'otp'|'password'|'ready';
export default function CollegeAdminActivation(){
  const {token:raw}=useLocalSearchParams<{token:string}>(); const token=raw??''; const {colors}=useRollCallTheme(); const insets=useSafeAreaInsets(); const {acceptSession}=useAuth();
  const [invitation,setInvitation]=useState<Invitation>(); const [step,setStep]=useState<Step>('college'); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [code,setCode]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [devOtp,setDevOtp]=useState('');
  const execute=async<T,>(task:()=>Promise<T>,done:(value:T)=>void)=>{setBusy(true);setError('');try{done(await task());}catch(reason){setError(reason instanceof AuthApiError?reason.message:'The request could not be completed.');}finally{setBusy(false);}};
  useEffect(()=>{let active=true;if(!token)return;void onboardingClient.get(token).then((value)=>{if(!active)return;setInvitation(value);setName(value.adminName??'');setStep(value.otpVerified?'password':value.adminName?'otp':value.collegeConfirmed?'details':'college');}).catch((reason)=>{if(active)setError(reason instanceof AuthApiError?reason.message:'The request could not be completed.');});return()=>{active=false;};},[token]);
  const percent=step==='college'?20:step==='details'?40:step==='otp'?60:step==='password'?80:100;
  if(!invitation&&!error)return <View style={{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background}}><Text style={[typography.body,{color:colors.textSecondary}]}>Preparing your workspace…</Text></View>;
  const content=invitation?<Card elevated><View style={{gap:spacing.xs}}><Text accessibilityRole="header" style={[typography.largeTitle,{color:colors.textPrimary}]}>Activate your workspace</Text><Text style={[typography.body,{color:colors.textSecondary}]}>Secure College Admin setup for {invitation.workspace.name}</Text></View><Progress value={percent} label={`Setup ${percent}% complete`}/>
    {error?<AlertBanner title="Unable to continue" message={error} tone="error"/>:null}
    {step==='college'?<View style={{gap:spacing.lg}}><Text style={[typography.heading,{color:colors.textPrimary}]}>Confirm approved college</Text><TextField label="College name" value={invitation.approvedCollege.name} editable={false}/><TextField label="Legal name" value={invitation.approvedCollege.legalName} editable={false}/><TextField label="Application reference" value={invitation.approvedCollege.applicationReference} editable={false}/><Button label="This information is correct" loading={busy} onPress={()=>void execute(()=>onboardingClient.confirmCollege(token),(value)=>{setInvitation(value);setStep('details');})}/></View>:null}
    {step==='details'?<View style={{gap:spacing.lg}}><Text style={[typography.heading,{color:colors.textPrimary}]}>Your admin account</Text><TextField label="Invited email" value={invitation.email} editable={false}/><TextField label="Full name" value={name} onChangeText={setName} required/><TextField label="Phone (optional)" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Button label="Continue to verification" disabled={!name.trim()} loading={busy} onPress={()=>void execute(()=>onboardingClient.saveDetails(token,name,phone),(value)=>{setInvitation(value);void execute(()=>onboardingClient.sendOtp(token),(sent)=>{setDevOtp(sent.developmentOtp??'');setStep('otp');});})}/></View>:null}
    {step==='otp'?<View style={{gap:spacing.lg}}><Text style={[typography.heading,{color:colors.textPrimary}]}>Verify your email</Text><Text style={[typography.body,{color:colors.textSecondary}]}>Enter the 6-digit code sent to {invitation.email}.</Text>{devOtp?<AlertBanner title="Development verification code" message={devOtp} tone="info"/>:null}<TextField label="Verification code" value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} required/><Button label="Verify email" disabled={code.length!==6} loading={busy} onPress={()=>void execute(()=>onboardingClient.verifyOtp(token,code),()=>setStep('password'))}/><Button label="Send another code" variant="text" onPress={()=>void execute(()=>onboardingClient.sendOtp(token),(sent)=>setDevOtp(sent.developmentOtp??''))}/></View>:null}
    {step==='password'?<View style={{gap:spacing.lg}}><Text style={[typography.heading,{color:colors.textPrimary}]}>Create your password</Text><Text style={[typography.bodySmall,{color:colors.textSecondary}]}>Use at least 12 characters with uppercase, lowercase, a number, and a symbol.</Text><TextField label="Password" value={password} onChangeText={setPassword} password autoComplete="new-password" required/><TextField label="Confirm password" value={confirm} onChangeText={setConfirm} password autoComplete="new-password" required/><Button label="Activate College Admin account" disabled={!password||!confirm} loading={busy} onPress={()=>void execute(()=>onboardingClient.activate(token,password,confirm),async(session)=>{await acceptSession(session);setStep('ready');})}/></View>:null}
    {step==='ready'?<View style={{gap:spacing.lg}}><AlertBanner title="Workspace activated" message="Your College Admin account is ready." tone="success"/><Button label="Open College Admin dashboard" onPress={()=>router.replace('/protected' as Href)}/></View>:null}
  </Card>:null;
  return <KeyboardAvoidingView style={{flex:1,backgroundColor:colors.background}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{flexGrow:1,justifyContent:'center',paddingHorizontal:spacing.lg,paddingTop:Math.max(insets.top,spacing.xl),paddingBottom:Math.max(insets.bottom,spacing.xl)}}><View style={{width:'100%',maxWidth:620,alignSelf:'center'}}>{content}{!invitation&&error?<AlertBanner title="Activation link unavailable" message={error} tone="error" action={<Button label="Back to sign in" variant="text" onPress={()=>router.replace('/login' as Href)}/>}/>:null}</View></ScrollView></KeyboardAvoidingView>;
}
