import React, { useState } from 'react';
import { Pressable, Switch, Text, TextInput, View, type TextInputProps } from 'react-native';
import { radii, sizing, spacing, typography } from '../tokens';
import { useRollCallTheme } from '../theme-provider';

export function TextField({ label, error, success, required, password, ...props }: TextInputProps & { label: string; error?: string; success?: string; required?: boolean; password?: boolean }) {
  const { colors } = useRollCallTheme(); const [focused, setFocused] = useState(false); const [revealed, setRevealed] = useState(false); const message = error ?? success; const messageColor = error ? colors.error : colors.success;
  return <View style={{ gap: spacing.sm }}><Text style={[typography.label, { color: colors.textPrimary }]}>{label}{required ? ' *' : ''}</Text><View style={{ flexDirection: 'row', minHeight: sizing.inputHeight, borderRadius: radii.md, borderWidth: focused || error ? 2 : 1, borderColor: error ? colors.error : focused ? colors.focusRing : colors.border, backgroundColor: props.editable === false ? colors.surfaceSecondary : colors.surface, alignItems: 'center' }}><TextInput accessibilityLabel={label} accessibilityState={{ disabled: props.editable === false }} allowFontScaling {...props} secureTextEntry={password && !revealed} onFocus={(event) => { setFocused(true); props.onFocus?.(event); }} onBlur={(event) => { setFocused(false); props.onBlur?.(event); }} placeholderTextColor={colors.textMuted} style={[typography.body, { flex: 1, minHeight: sizing.inputHeight, paddingHorizontal: spacing.lg, color: colors.textPrimary }, props.style]} />{password ? <Pressable accessibilityRole="button" accessibilityLabel={revealed ? 'Hide password' : 'Show password'} onPress={() => setRevealed(!revealed)} style={{ minWidth: sizing.touchTarget, minHeight: sizing.touchTarget, alignItems: 'center', justifyContent: 'center' }}><Text style={[typography.caption, { color: colors.primary }]}>{revealed ? 'Hide' : 'Show'}</Text></Pressable> : null}</View>{message ? <Text accessibilityLiveRegion="polite" style={[typography.caption, { color: messageColor }]}>{message}</Text> : null}</View>;
}

export function SearchField(props: Omit<TextInputProps, 'accessibilityLabel'>) { return <TextField label="Search" placeholder="Search" returnKeyType="search" {...props} />; }

export function SelectField({ label, value, placeholder = 'Choose an option', disabled, onPress }: { label: string; value?: string; placeholder?: string; disabled?: boolean; onPress?: () => void }) {
  const { colors } = useRollCallTheme(); return <View style={{ gap: spacing.sm }}><Text style={[typography.label, { color: colors.textPrimary }]}>{label}</Text><Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={(state) => ({ minHeight: sizing.inputHeight, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, backgroundColor: state.pressed ? colors.surfaceSecondary : colors.surface, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', opacity: disabled ? 0.48 : 1 })}><Text style={[typography.body, { color: value ? colors.textPrimary : colors.textMuted }]}>{value ?? placeholder}</Text><Text accessibilityElementsHidden style={[typography.heading, { color: colors.textMuted }]}>⌄</Text></Pressable></View>;
}

export function Checkbox({ label, checked, onChange, disabled = false }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) {
  const { colors } = useRollCallTheme(); return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked, disabled }} disabled={disabled} onPress={() => onChange(!checked)} style={({ pressed }) => ({ minHeight: sizing.touchTarget, flexDirection: 'row', alignItems: 'center', gap: spacing.md, opacity: disabled ? 0.48 : pressed ? 0.75 : 1 })}><View style={{ width: sizing.controlSm, height: sizing.controlSm, borderRadius: radii.sm, borderWidth: 2, borderColor: checked ? colors.primary : colors.border, backgroundColor: checked ? colors.primary : 'transparent', alignItems: 'center', justifyContent: 'center' }}>{checked ? <Text style={{ color: colors.textInverse, fontWeight: '700' }}>✓</Text> : null}</View><Text style={[typography.body, { color: colors.textPrimary }]}>{label}</Text></Pressable>;
}

export function SwitchField({ label, detail, value, onValueChange, disabled }: { label: string; detail?: string; value: boolean; onValueChange: (value: boolean) => void; disabled?: boolean }) {
  const { colors } = useRollCallTheme(); return <View style={{ minHeight: sizing.touchTarget, flexDirection: 'row', alignItems: 'center', gap: spacing.lg, opacity: disabled ? 0.48 : 1 }}><View style={{ flex: 1, gap: spacing.xs }}><Text style={[typography.body, { color: colors.textPrimary }]}>{label}</Text>{detail ? <Text style={[typography.caption, { color: colors.textMuted }]}>{detail}</Text> : null}</View><Switch accessibilityLabel={label} value={value} disabled={disabled} onValueChange={onValueChange} trackColor={{ false: colors.border, true: colors.primary }} /></View>;
}

export function SegmentedControl<T extends string>({ value, options, onChange }: { value: T; options: readonly { label: string; value: T }[]; onChange: (value: T) => void }) {
  const { colors } = useRollCallTheme(); return <View accessibilityRole="radiogroup" style={{ flexDirection: 'row', padding: spacing.xs, borderRadius: radii.md, backgroundColor: colors.surfaceSecondary }}>{options.map((option) => { const selected = value === option.value; return <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{ selected }} onPress={() => onChange(option.value)} style={({ pressed }) => ({ flex: 1, minHeight: 40, paddingHorizontal: spacing.md, borderRadius: radii.sm, alignItems: 'center', justifyContent: 'center', backgroundColor: selected ? colors.surface : 'transparent', opacity: pressed ? 0.72 : 1 })}><Text numberOfLines={1} style={[typography.label, { color: selected ? colors.textPrimary : colors.textMuted }]}>{option.label}</Text></Pressable>; })}</View>;
}

export function DateTimeField({ label, value, onPress }: { label: string; value: string; onPress?: () => void }) { return <SelectField label={label} value={value} onPress={onPress} />; }
