import { useState } from 'react';
import { router, type Href } from 'expo-router';
import { View } from 'react-native';
import { Button } from '@/design-system/components/core';
import { BottomSheet, Confirmation } from '@/design-system/components/feedback';
import { TextField } from '@/design-system/components/forms';
import { spacing } from '@/design-system/tokens';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { ManagementHeader, ManagementRow, RelationshipSection } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function AcademicYears() {
  const data = useHodManagement(); const [sheet, setSheet] = useState(false); const [editingId, setEditingId] = useState<string>(); const [name, setName] = useState(''); const [period, setPeriod] = useState(''); const [activate, setActivate] = useState<string>(); const [archive, setArchive] = useState<string>();
  const openAdd = () => { setEditingId(undefined); setName(''); setPeriod(''); setSheet(true); }; const openEdit = (id: string) => { const year = data.academicYears.find((item) => item.id === id); if (!year) return; setEditingId(id); setName(year.name); setPeriod(year.period); setSheet(true); };
  const save = () => { if (editingId) data.updateAcademicYear(editingId, name.trim(), period.trim()); else data.addAcademicYear(name.trim(), period.trim()); setSheet(false); };
  return <HodShell activeKey="department" title="Academic years" subtitle="Academic structure" back backFallback="/hod/management"><PageContainer width="detail"><ManagementHeader title="Academic years" description="One academic year is marked current for department operations." action="Add academic year" onAction={openAdd} /><RelationshipSection title="Years">{data.academicYears.map((year) => <ManagementRow key={year.id} title={year.name} detail={year.period} status={year.current ? 'Current' : year.status} actions={<View style={{ flexDirection: 'row' }}><Button label="Edit" variant="text" onPress={() => openEdit(year.id)} />{!year.current ? <Button label={year.status === 'Active' ? 'Archive' : 'Archived'} variant="text" disabled={year.status !== 'Active'} onPress={() => setArchive(year.id)} /> : null}{!year.current && year.status === 'Active' ? <Button label="Make current" variant="text" onPress={() => setActivate(year.id)} /> : null}</View>} />)}</RelationshipSection><RelationshipSection title="Related structure"><ManagementRow title="Semesters" detail={`${data.semesters.length} configured`} onPress={() => router.push('/hod/management/semesters' as Href)} /><ManagementRow title="Batches" detail={`${data.batches.length} configured`} onPress={() => router.push('/hod/management/batches' as Href)} /></RelationshipSection><BottomSheet visible={sheet} title={editingId ? 'Edit academic year' : 'Add academic year'} onDismiss={() => setSheet(false)}><View style={{ gap: spacing.lg }}><TextField label="Academic year" placeholder="2027–28" value={name} onChangeText={setName} /><TextField label="Start and end period" placeholder="July 2027 – June 2028" value={period} onChangeText={setPeriod} /><Button label={editingId ? 'Save changes' : 'Add academic year'} disabled={!name.trim() || !period.trim()} onPress={save} /></View></BottomSheet><Confirmation visible={Boolean(activate)} title="Make this the current academic year?" message="The current indicator will move to the selected year. Existing records remain unchanged." confirmLabel="Make current" onDismiss={() => setActivate(undefined)} onConfirm={() => { if (activate) data.activateAcademicYear(activate); setActivate(undefined); }} /><Confirmation visible={Boolean(archive)} title="Archive academic year?" message="Existing academic relationships remain available, but the year will no longer be active." confirmLabel="Archive" destructive onDismiss={() => setArchive(undefined)} onConfirm={() => { if (archive) data.archiveAcademicYear(archive); setArchive(undefined); }} /></PageContainer></HodShell>;
}
