import { useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { View } from 'react-native';
import { Button } from '@/design-system/components/core';
import { AlertBanner, Confirmation } from '@/design-system/components/feedback';
import { spacing } from '@/design-system/tokens';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { ManagementHeader, ManagementRow, OptionPicker, RelationshipSection } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function ClassTeacherAssignments() {
  const params = useLocalSearchParams<{ section?: string }>(); const data = useHodManagement(); const [sectionId, setSection] = useState(params.section ?? ''); const [lecturerId, setLecturer] = useState(''); const [confirm, setConfirm] = useState(false); const [remove, setRemove] = useState<string>(); const [success, setSuccess] = useState(''); const section = data.sections.find((item) => item.id === sectionId); const current = data.lecturers.find((item) => item.id === section?.classTeacherId); const next = data.lecturers.find((item) => item.id === lecturerId);
  const apply = () => { if (!sectionId || !lecturerId) return; data.assignClassTeacher(sectionId, lecturerId); setSuccess(`${next?.name} is now Class Teacher for ${section?.name}.`); setConfirm(false); };
  return <HodShell activeKey="department" title="Class Teachers" subtitle="Class responsibility" back backFallback="/hod/management"><PageContainer width="full"><ManagementHeader title="Assign Class Teacher" description="Class Teacher responsibility is separate from subject teaching assignments." />{success ? <AlertBanner title="Class Teacher updated" message={success} tone="success" /> : null}<View style={{ maxWidth: 680, width: '100%', gap: spacing.lg }}><OptionPicker label="Class / Section" value={sectionId} options={data.sections.map((item) => ({ value: item.id, label: item.name, detail: data.semesters.find((semester) => semester.id === item.semesterId)?.name }))} onChange={(value) => { setSection(value); setLecturer(''); }} />{section ? <AlertBanner title={current ? 'Current Class Teacher' : 'Class Teacher not assigned'} message={current ? `${current.name} is responsible for ${section.name}.` : `Choose a lecturer or HOD / Me for ${section.name}.`} tone={current ? 'info' : 'warning'} /> : null}<OptionPicker label="New Class Teacher" value={lecturerId} disabled={!sectionId} options={data.lecturers.filter((item) => item.status === 'Active').map((item) => ({ value: item.id, label: item.id === 'me' ? 'HOD / Me' : item.name, detail: item.employeeId }))} onChange={setLecturer} /><Button label={current ? 'Review change' : 'Assign Class Teacher'} disabled={!sectionId || !lecturerId || lecturerId === current?.id} onPress={() => setConfirm(true)} /></View><RelationshipSection title="Current responsibilities">{data.sections.map((item) => { const teacher = data.lecturers.find((lecturer) => lecturer.id === item.classTeacherId); return <ManagementRow key={item.id} title={item.name} detail={`${data.semesters.find((semester) => semester.id === item.semesterId)?.name} · ${data.batches.find((batch) => batch.id === item.batchId)?.name}`} meta={`Class Teacher: ${teacher?.name ?? 'Not assigned'}`} status={teacher ? 'Assigned' : 'Unassigned'} actions={teacher ? <Button label="Remove" variant="text" onPress={() => setRemove(item.id)} /> : undefined} />; })}</RelationshipSection><Confirmation visible={confirm} title={current ? 'Change Class Teacher?' : 'Assign Class Teacher?'} message={`${section?.name}: ${current ? `${current.name} → ` : ''}${next?.name}. Previous responsibility history remains intact.`} confirmLabel={current ? 'Change Class Teacher' : 'Assign'} onDismiss={() => setConfirm(false)} onConfirm={apply} /><Confirmation visible={Boolean(remove)} title="Remove Class Teacher?" message="The class will remain active but have no current Class Teacher until another person is assigned." confirmLabel="Remove" destructive onDismiss={() => setRemove(undefined)} onConfirm={() => { if (remove) data.assignClassTeacher(remove, undefined); setRemove(undefined); }} /></PageContainer></HodShell>;
}
