import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, Text, View } from 'react-native';
import { router, type Href } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { authClient } from '@/auth/auth-client';
import { useAuth } from '@/auth/auth-provider';
import { AuthApiError } from '@/auth/types';
import { Button, Card } from '@/design-system/components/core';
import { AlertBanner } from '@/design-system/components/feedback';
import { TextField } from '@/design-system/components/forms';
import { sizing, spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
export default function SuperAdminLogin(){const{colors}=useRollCallTheme();const insets=useSafeAreaInsets();const{acceptSession}=useAuth();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError('');try{const session=await authClient.superAdminLogin(email.trim(),password);await acceptSession(session);router.replace('/protected' as Href);}catch(reason){setError(reason instanceof AuthApiError?reason.message:'Super Admin sign-in failed.');}finally{setBusy(false);}};return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,backgroundColor:colors.background}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{flexGrow:1,justifyContent:'center',paddingHorizontal:spacing.lg,paddingTop:Math.max(insets.top,spacing.xl),paddingBottom:Math.max(insets.bottom,spacing.xl)}}><View style={{width:'100%',maxWidth:460,alignSelf:'center',gap:spacing.xl}}><View style={{alignItems:'center',gap:spacing.md}}><View style={{width:52,height:52,borderRadius:16,backgroundColor:colors.surfaceSecondary,alignItems:'center',justifyContent:'center'}}><Ionicons name="shield-checkmark-outline" size={sizing.iconLg} color={colors.primary}/></View><View style={{gap:spacing.xs,alignItems:'center'}}><Text accessibilityRole="header" style={[typography.largeTitle,{color:colors.textPrimary}]}>Super Admin</Text><Text style={[typography.body,{color:colors.textSecondary,textAlign:'center'}]}>Platform owner access for RollCall operations.</Text></View></View><Card elevated>{error?<AlertBanner title={error.includes('rate')?'Access temporarily limited':'Unable to sign in'} message={error} tone="error"/>:null}<TextField label="Email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" required/><TextField label="Password" value={password} onChangeText={setPassword} password autoComplete="current-password" required onSubmitEditing={submit}/><Button label="Sign in" loading={busy} disabled={!email.trim()||!password} onPress={submit}/></Card><Text style={[typography.caption,{color:colors.textMuted,textAlign:'center'}]}>Dedicated platform access · Normal college accounts are not accepted</Text></View></ScrollView></KeyboardAvoidingView>}
