import { randomUUID } from 'node:crypto';
import { AppError, forbidden } from './errors.mjs';
import { Roles } from './roles.mjs';

function requireLecturer(session) {
  if (session.user.role !== Roles.LECTURER) throw forbidden('Lecturer access is required.');
  return session.user;
}

function statusFor(percentage) { return percentage < 65 ? 'low' : percentage < 75 ? 'warning' : 'good'; }
function classSummary(row) { return { id: row.id, subjectCode: row.subject_code, subjectName: row.subject_name, batchName: row.batch_name, semester: row.semester, schedule: row.schedule_text, nextSessionAt: row.next_session_at, studentCount: row.student_count, completedSessions: row.completed_sessions, requiresAttendance: Boolean(row.next_session_at && Date.parse(row.next_session_at) <= Date.now() + 90 * 60 * 1000) }; }
function sessionSummary(row) { return { id: row.id, classId: row.class_id, subjectCode: row.subject_code, subjectName: row.subject_name, batchName: row.batch_name, method: row.method, status: row.status, scheduledAt: row.scheduled_at, submittedAt: row.submitted_at, correctedAt: row.corrected_at, present: row.present_count, absent: row.absent_count, total: row.total_count }; }

export function createLecturerService(db) {
  const classesFor = db.prepare(`SELECT c.*, COUNT(DISTINCT e.student_id) student_count, COUNT(DISTINCT CASE WHEN s.status='COMPLETED' THEN s.id END) completed_sessions FROM lecturer_classes c LEFT JOIN class_enrollments e ON e.class_id=c.id LEFT JOIN attendance_sessions s ON s.class_id=c.id WHERE c.lecturer_id=? AND c.college_id=? AND c.status='ACTIVE' GROUP BY c.id ORDER BY c.next_session_at IS NULL, c.next_session_at, c.subject_name`);
  const ownedClass = db.prepare(`SELECT c.*, u.name lecturer_name, COUNT(DISTINCT e.student_id) student_count, COUNT(DISTINCT CASE WHEN s.status='COMPLETED' THEN s.id END) completed_sessions FROM lecturer_classes c JOIN users u ON u.id=c.lecturer_id LEFT JOIN class_enrollments e ON e.class_id=c.id LEFT JOIN attendance_sessions s ON s.class_id=c.id WHERE c.id=? AND c.lecturer_id=? AND c.college_id=? GROUP BY c.id`);
  const roster = db.prepare(`SELECT u.id, u.name, e.roll_number, COUNT(r.session_id) marked_count, SUM(CASE WHEN r.status='PRESENT' THEN 1 ELSE 0 END) present_count FROM class_enrollments e JOIN users u ON u.id=e.student_id LEFT JOIN attendance_sessions s ON s.class_id=e.class_id AND s.status='COMPLETED' LEFT JOIN attendance_records r ON r.session_id=s.id AND r.student_id=u.id WHERE e.class_id=? GROUP BY u.id, e.roll_number ORDER BY e.roll_number`);
  const history = db.prepare(`SELECT s.*, c.subject_code, c.subject_name, c.batch_name, SUM(CASE WHEN r.status='PRESENT' THEN 1 ELSE 0 END) present_count, SUM(CASE WHEN r.status='ABSENT' THEN 1 ELSE 0 END) absent_count, COUNT(r.student_id) total_count FROM attendance_sessions s JOIN lecturer_classes c ON c.id=s.class_id LEFT JOIN attendance_records r ON r.session_id=s.id WHERE s.lecturer_id=? AND s.college_id=? GROUP BY s.id ORDER BY s.scheduled_at DESC`);
  const ownedSession = db.prepare(`SELECT s.*, c.subject_code, c.subject_name, c.batch_name FROM attendance_sessions s JOIN lecturer_classes c ON c.id=s.class_id WHERE s.id=? AND s.lecturer_id=? AND s.college_id=?`);
  const recordsFor = db.prepare('SELECT student_id, status FROM attendance_records WHERE session_id=?');

  function getClass(session, classId) { const user=requireLecturer(session); const row=ownedClass.get(classId,user.id,user.college.id); if(!row) throw new AppError(404,'CLASS_NOT_FOUND','Class not found or not assigned to this lecturer.'); return row; }
  function getSession(session, sessionId) { const user=requireLecturer(session); const row=ownedSession.get(sessionId,user.id,user.college.id); if(!row) throw new AppError(404,'SESSION_NOT_FOUND','Attendance session not found.'); return row; }
  function students(session,classId) { getClass(session,classId); return roster.all(classId).map(row=>{ const percentage=row.marked_count ? Math.round(row.present_count*100/row.marked_count):100; return { id:row.id,name:row.name,rollNumber:row.roll_number,attendancePercentage:percentage,attendanceStatus:statusFor(percentage),presentCount:row.present_count||0,absentCount:(row.marked_count||0)-(row.present_count||0) }; }); }

  return {
    listClasses(session) { const user=requireLecturer(session); return classesFor.all(user.id,user.college.id).map(classSummary); },
    overview(session) { const classes=this.listClasses(session); const sessions=history.all(session.user.id,session.user.college.id).filter(x=>x.status==='COMPLETED').slice(0,3).map(sessionSummary); return { today:classes.filter(x=>x.nextSessionAt&&new Date(x.nextSessionAt).toDateString()===new Date().toDateString()), upcoming:classes.filter(x=>x.nextSessionAt&&Date.parse(x.nextSessionAt)>Date.now()).slice(0,3), requiringAttendance:classes.filter(x=>x.requiresAttendance), recentSessions:sessions }; },
    classDetails(session,classId) { const row=getClass(session,classId); return {...classSummary(row),lecturer:{id:row.lecturer_id,name:row.lecturer_name}}; },
    roster: students,
    student(session,classId,studentId) { const student=students(session,classId).find(x=>x.id===studentId); if(!student) throw new AppError(404,'STUDENT_NOT_FOUND','Student is not enrolled in this class.'); const entries=db.prepare(`SELECT s.id,s.scheduled_at,r.status FROM attendance_sessions s JOIN attendance_records r ON r.session_id=s.id WHERE s.class_id=? AND s.status='COMPLETED' AND r.student_id=? ORDER BY s.scheduled_at DESC LIMIT 12`).all(classId,studentId); return {...student,history:entries.map(x=>({sessionId:x.id,date:x.scheduled_at,status:x.status}))}; },
    startSession(session,classId,input) { const user=requireLecturer(session); getClass(session,classId); const method=input.method; if(!['MANUAL','FACE'].includes(method)) throw new AppError(422,'VALIDATION_ERROR','Choose a valid attendance method.'); const scheduledAt=input.scheduledAt&&Number.isFinite(Date.parse(input.scheduledAt))?new Date(input.scheduledAt).toISOString():new Date().toISOString(); const existing=db.prepare(`SELECT id FROM attendance_sessions WHERE class_id=? AND lecturer_id=? AND status='DRAFT'`).get(classId,user.id); if(existing) return this.session(session,existing.id); const id=randomUUID(), now=new Date().toISOString(); db.prepare(`INSERT INTO attendance_sessions (id,class_id,lecturer_id,college_id,method,status,scheduled_at,created_at,updated_at) VALUES (?,?,?,?,?,'DRAFT',?,?,?)`).run(id,classId,user.id,user.college.id,method,scheduledAt,now,now); return this.session(session,id); },
    session(session,sessionId) { const row=getSession(session,sessionId); return {...sessionSummary({...row,present_count:0,absent_count:0,total_count:0}),records:Object.fromEntries(recordsFor.all(sessionId).map(x=>[x.student_id,x.status])),students:students(session,row.class_id)}; },
    submit(session,sessionId,input,{correction=false}={}) { const row=getSession(session,sessionId); if(!correction&&row.status==='COMPLETED') throw new AppError(409,'SESSION_ALREADY_SUBMITTED','This attendance session has already been submitted.'); if(correction&&row.status!=='COMPLETED') throw new AppError(409,'SESSION_NOT_COMPLETED','Only completed attendance can be corrected.'); const enrolled=new Set(students(session,row.class_id).map(x=>x.id)); const records=Array.isArray(input.records)?input.records:[]; if(records.length!==enrolled.size||records.some(x=>!enrolled.has(x.studentId)||!['PRESENT','ABSENT'].includes(x.status))) throw new AppError(422,'INCOMPLETE_ATTENDANCE','Every enrolled student must have one valid attendance mark.'); const unique=new Set(records.map(x=>x.studentId)); if(unique.size!==records.length) throw new AppError(422,'INVALID_ATTENDANCE','Duplicate student marks are not allowed.'); const now=new Date().toISOString(); db.transaction(()=>{ db.prepare('DELETE FROM attendance_records WHERE session_id=?').run(sessionId); const insert=db.prepare('INSERT INTO attendance_records (session_id,student_id,status,updated_at) VALUES (?,?,?,?)'); records.forEach(x=>insert.run(sessionId,x.studentId,x.status,now)); db.prepare(`UPDATE attendance_sessions SET status='COMPLETED',submitted_at=COALESCE(submitted_at,?),corrected_at=?,correction_note=?,updated_at=? WHERE id=?`).run(now,correction?now:null,correction?(input.note||'Lecturer correction'):null,now,sessionId); })(); return this.session(session,sessionId); },
    history(session) { const user=requireLecturer(session); return history.all(user.id,user.college.id).map(sessionSummary); },
  };
}
