import { createHmac, randomBytes, randomInt, randomUUID } from 'node:crypto';
import { AppError, forbidden } from './errors.mjs';
import { hashPassword } from './password.mjs';
import { createEmailService } from './email-service.mjs';

const digest = (value, secret) => createHmac('sha256', secret).update(value).digest('base64url');
const text = (value, field, max = 160) => { const result = String(value ?? '').trim(); if (!result || result.length > max) throw new AppError(400, 'VALIDATION_ERROR', `${field} is required.`); return result; };
const email = (value) => { const result = text(value, 'Admin email', 254).toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result)) throw new AppError(400, 'VALIDATION_ERROR', 'Enter a valid admin email.'); return result; };
const passwordError = (value) => typeof value !== 'string' || value.length < 12 || !/[a-z]/.test(value) || !/[A-Z]/.test(value) || !/\d/.test(value) || !/[^A-Za-z0-9]/.test(value);

export function createOnboardingService(db, config, auth, emailTransport) {
  const mail = createEmailService(config, emailTransport);
  const invitationByToken = db.prepare(`SELECT i.*, w.name workspace_name, w.state workspace_state, w.college_id,
    a.legal_name, a.reference application_reference FROM invitations i JOIN workspaces w ON w.id=i.workspace_id
    JOIN college_applications a ON a.id=w.application_id WHERE i.token_hash=?`);
  const safeInvitation = (row) => ({ invitationId: row.id, workspace: { id: row.workspace_id, name: row.workspace_name, state: row.workspace_state }, approvedCollege: { name: row.workspace_name, legalName: row.legal_name, applicationReference: row.application_reference }, email: row.email, adminName: row.admin_name, collegeConfirmed: Boolean(row.college_confirmed_at), otpVerified: Boolean(row.otp_verified_at), expiresAt: row.expires_at, status: row.status, pinSupported: false });
  const resolve = (token, { allowExpired = false } = {}) => {
    const row = invitationByToken.get(digest(text(token, 'Invitation token', 512), config.sessionSecret));
    if (!row) throw new AppError(404, 'INVITATION_NOT_FOUND', 'This activation invitation is invalid.');
    if (row.status === 'ACCEPTED') throw new AppError(409, 'ALREADY_ACTIVATED', 'This invitation has already been used. Sign in instead.');
    if (row.status === 'REVOKED') throw new AppError(410, 'INVITATION_REVOKED', 'This invitation was replaced. Use the latest email.');
    if (!allowExpired && Date.parse(row.expires_at) <= Date.now()) { db.prepare("UPDATE invitations SET status='EXPIRED', updated_at=? WHERE id=?").run(new Date().toISOString(), row.id); throw new AppError(410, 'INVITATION_EXPIRED', 'This invitation has expired. Request a new activation email.'); }
    return row;
  };
  const createInvitation = async (workspaceId, targetEmail, now = new Date()) => {
    const raw = randomBytes(32).toString('base64url'); const id = randomUUID(); const stamp = now.toISOString();
    db.prepare(`INSERT INTO invitations (id, workspace_id, email, role, token_hash, status, expires_at, created_at, updated_at) VALUES (?,?,?,?,?,'PENDING',?,?,?)`)
      .run(id, workspaceId, targetEmail, 'COLLEGE_ADMIN', digest(raw, config.sessionSecret), new Date(now.getTime() + config.invitationTtlSeconds * 1000).toISOString(), stamp, stamp);
    const workspace = db.prepare('SELECT name FROM workspaces WHERE id=?').get(workspaceId); const activationUrl = `${config.onboardingBaseUrl}/${raw}`;
    try { await mail.invitation(targetEmail, workspace.name, activationUrl); }
    catch (error) { db.prepare("UPDATE invitations SET status='REVOKED',updated_at=? WHERE id=?").run(new Date().toISOString(),id); throw error; }
    return { id, activationUrl, raw };
  };
  return {
    async provision(input, paymentSecret) {
      if (!config.paymentWebhookSecret || paymentSecret !== config.paymentWebhookSecret) throw forbidden('The payment event signature is invalid.');
      const paymentEventId = text(input.paymentEventId, 'Payment event ID'); const reference = text(input.applicationReference, 'Application reference');
      const existing = db.prepare(`SELECT w.id workspace_id, w.state, i.id invitation_id, a.admin_email FROM college_applications a JOIN workspaces w ON w.application_id=a.id LEFT JOIN invitations i ON i.workspace_id=w.id AND i.status='PENDING' WHERE a.payment_event_id=? OR a.reference=? ORDER BY i.created_at DESC LIMIT 1`).get(paymentEventId, reference);
      if (existing) { const recovered=existing.invitation_id?null:await createInvitation(existing.workspace_id,existing.admin_email); return { idempotent: true, workspace: { id: existing.workspace_id, state: existing.state }, invitationId: existing.invitation_id??recovered.id, ...(config.exposeDevelopmentSecrets&&recovered?{developmentActivationUrl:recovered.activationUrl}:{}) }; }
      const collegeName = text(input.collegeName, 'College name'); const legalName = text(input.legalName ?? input.collegeName, 'Legal name'); const adminEmail = email(input.adminEmail); const adminName = text(input.adminName, 'Admin name'); const planCode = text(input.planCode ?? 'ROLLCALL_V1', 'Plan code');
      const ids = { application: randomUUID(), college: randomUUID(), workspace: randomUUID(), subscription: randomUUID() }; const now = new Date().toISOString();
      db.transaction(() => {
        db.prepare('INSERT INTO college_applications (id,reference,college_name,legal_name,admin_email,admin_name,approved_at,payment_event_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(ids.application, reference, collegeName, legalName, adminEmail, adminName, now, paymentEventId, now);
        db.prepare("INSERT INTO colleges (id,name,status,created_at,updated_at) VALUES (?,?,'DISABLED',?,?)").run(ids.college, collegeName, now, now);
        db.prepare("INSERT INTO workspaces (id,college_id,application_id,name,state,created_at,updated_at) VALUES (?,?,?,?,'PENDING',?,?)").run(ids.workspace, ids.college, ids.application, collegeName, now, now);
        db.prepare("UPDATE workspaces SET state='PAYMENT_CONFIRMED',updated_at=? WHERE id=?").run(now, ids.workspace);
        db.prepare("INSERT INTO subscriptions (id,workspace_id,payment_event_id,plan_code,status,created_at,updated_at) VALUES (?,?,?,?, 'ACTIVE',?,?)").run(ids.subscription, ids.workspace, paymentEventId, planCode, now, now);
        db.prepare("UPDATE workspaces SET state='PROVISIONING',updated_at=? WHERE id=?").run(now, ids.workspace);
        db.prepare("UPDATE workspaces SET state='READY_FOR_ADMIN',updated_at=? WHERE id=?").run(now, ids.workspace);
      })();
      const invitation = await createInvitation(ids.workspace, adminEmail);
      return { idempotent: false, workspace: { id: ids.workspace, state: 'READY_FOR_ADMIN' }, invitationId: invitation.id, ...(config.exposeDevelopmentSecrets ? { developmentActivationUrl: invitation.activationUrl } : {}) };
    },
    get(token) { return safeInvitation(resolve(token)); },
    confirmCollege(token) { const row=resolve(token); const now=new Date().toISOString(); db.prepare('UPDATE invitations SET college_confirmed_at=?,updated_at=? WHERE id=?').run(now,now,row.id); return safeInvitation(resolve(token)); },
    details(token, input) { const row=resolve(token); if (!row.college_confirmed_at) throw new AppError(409,'COLLEGE_CONFIRMATION_REQUIRED','Confirm the approved college details first.'); const now=new Date().toISOString(); db.prepare('UPDATE invitations SET admin_name=?,phone=?,updated_at=? WHERE id=?').run(text(input.name,'Full name'), String(input.phone??'').trim().slice(0,32)||null, now,row.id); return safeInvitation(resolve(token)); },
    async sendOtp(token) { const row=resolve(token); if (!row.admin_name) throw new AppError(409,'ADMIN_DETAILS_REQUIRED','Complete your account details first.'); const latest=db.prepare('SELECT * FROM otp_challenges WHERE invitation_id=? ORDER BY created_at DESC LIMIT 1').get(row.id); if (latest && Date.now()-Date.parse(latest.last_sent_at)<30000) throw new AppError(429,'OTP_COOLDOWN','Wait 30 seconds before requesting another code.'); if (latest && latest.resend_count>=5) throw new AppError(429,'OTP_RATE_LIMIT','Too many verification codes were requested. Try again later.'); const code=String(randomInt(0,1000000)).padStart(6,'0'); const now=new Date(); db.prepare('INSERT INTO otp_challenges (id,invitation_id,code_hash,expires_at,attempts,resend_count,last_sent_at,created_at) VALUES (?,?,?,?,0,?,?,?)').run(randomUUID(),row.id,digest(code,config.sessionSecret),new Date(now.getTime()+config.otpTtlSeconds*1000).toISOString(),(latest?.resend_count??-1)+1,now.toISOString(),now.toISOString()); await mail.otp(row.email,code); return { sent:true, maskedEmail: row.email.replace(/^(.{2}).*(@.*)$/,'$1••••$2'), ...(config.exposeDevelopmentSecrets?{developmentOtp:code}:{}) }; },
    verifyOtp(token, input) { const row=resolve(token); const challenge=db.prepare('SELECT * FROM otp_challenges WHERE invitation_id=? ORDER BY created_at DESC LIMIT 1').get(row.id); if (!challenge || Date.parse(challenge.expires_at)<=Date.now()) throw new AppError(410,'OTP_EXPIRED','The verification code has expired. Request a new one.'); if (challenge.verified_at) return { verified:true }; if (challenge.attempts>=5) throw new AppError(429,'OTP_ATTEMPTS_EXCEEDED','Too many incorrect attempts. Request a new code.'); const valid=digest(String(input.code??''),config.sessionSecret)===challenge.code_hash; if (!valid) { db.prepare('UPDATE otp_challenges SET attempts=attempts+1 WHERE id=?').run(challenge.id); throw new AppError(400,'INVALID_OTP','The verification code is incorrect.'); } const now=new Date().toISOString(); db.transaction(()=>{db.prepare('UPDATE otp_challenges SET verified_at=? WHERE id=?').run(now,challenge.id);db.prepare('UPDATE invitations SET otp_verified_at=?,updated_at=? WHERE id=?').run(now,now,row.id);})(); return { verified:true }; },
    async activate(token, input) { const row=resolve(token); if (!row.college_confirmed_at||!row.admin_name||!row.otp_verified_at) throw new AppError(409,'ONBOARDING_INCOMPLETE','Complete college confirmation, account details, and email verification first.'); if (input.password!==input.confirmPassword) throw new AppError(400,'PASSWORD_MISMATCH','The passwords do not match.'); if (passwordError(input.password)) throw new AppError(400,'WEAK_PASSWORD','Use at least 12 characters with uppercase, lowercase, number, and symbol.'); if (db.prepare('SELECT id FROM users WHERE login_identifier=?').get(row.email)) throw new AppError(409,'ACCOUNT_EXISTS','An account already exists for this email. Sign in instead.'); const userId=randomUUID(), membershipId=randomUUID(), now=new Date().toISOString(), passwordHash=await hashPassword(input.password);
      db.transaction(()=>{db.prepare("INSERT INTO users (id,name,login_identifier,password_hash,role,college_id,status,created_at,updated_at) VALUES (?,?,?,?,'COLLEGE_ADMIN',?,'ACTIVE',?,?)").run(userId,row.admin_name,row.email,passwordHash,row.college_id,now,now);db.prepare("INSERT INTO workspace_memberships (id,workspace_id,user_id,role,status,created_at,updated_at) VALUES (?,?,?,'COLLEGE_ADMIN','ACTIVE',?,?)").run(membershipId,row.workspace_id,userId,now,now);db.prepare("UPDATE colleges SET status='ACTIVE',updated_at=? WHERE id=?").run(now,row.college_id);db.prepare("UPDATE workspaces SET state='ACTIVE',updated_at=? WHERE id=?").run(now,row.workspace_id);db.prepare("UPDATE invitations SET status='ACCEPTED',accepted_at=?,updated_at=? WHERE id=?").run(now,now,row.id);})();
      return auth.createSessionForUser(userId);
    },
    async resend(token) { const row=resolve(token,{allowExpired:true}); const now=new Date().toISOString(); db.prepare("UPDATE invitations SET status='REVOKED',updated_at=? WHERE id=?").run(now,row.id); const next=await createInvitation(row.workspace_id,row.email); return { sent:true,...(config.exposeDevelopmentSecrets?{developmentActivationUrl:next.activationUrl}:{})}; },
    workspace(session) { if (session.user.role!=='COLLEGE_ADMIN'||!session.user.workspace) throw forbidden(); const id=session.user.workspace.id; const row=db.prepare(`SELECT w.*,c.name college_name,s.plan_code,s.status subscription_status FROM workspaces w JOIN colleges c ON c.id=w.college_id LEFT JOIN subscriptions s ON s.workspace_id=w.id WHERE w.id=?`).get(id); if(!row) throw forbidden(); return {id:row.id,name:row.name,state:row.state,collegeId:row.college_id,subscription:row.plan_code?{planCode:row.plan_code,status:row.subscription_status}:null}; },
    setup(session) { const workspace=this.workspace(session); const count=(table)=>db.prepare(`SELECT COUNT(*) value FROM ${table} WHERE workspace_id=?`).get(workspace.id).value; const roleCount=(role)=>db.prepare("SELECT COUNT(*) value FROM workspace_memberships WHERE workspace_id=? AND role=? AND status='ACTIVE'").get(workspace.id,role).value; const items=[{key:'college-profile',label:'College profile confirmed',complete:true,count:1},{key:'academic-years',label:'Add an academic year',complete:count('academic_years')>0,count:count('academic_years')},{key:'departments',label:'Add departments',complete:count('departments')>0,count:count('departments')},{key:'hods',label:'Invite HODs',complete:roleCount('HOD')>0,count:roleCount('HOD')},{key:'lecturers',label:'Invite lecturers',complete:roleCount('LECTURER')>0,count:roleCount('LECTURER')},{key:'students',label:'Add students',complete:roleCount('STUDENT')>0,count:roleCount('STUDENT')}]; return {workspace,items,completed:items.filter(x=>x.complete).length,total:items.length}; }
  };
}
