import { randomUUID } from 'node:crypto';
import { AppError } from './errors.mjs';
import { Roles } from './roles.mjs';

const entryTypes = new Set(['CLASS','LAB','BREAK','LUNCH','REMEDIAL','ACTIVITY','PROJECT','SPECIAL']);
const changeKinds = new Set(['CHANGE','CANCELLED','SPECIAL','RESCHEDULED']);
const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const parse = (value) => { try { return value ? JSON.parse(value) : null; } catch { return null; } };
const isoToday = () => new Date().toISOString().slice(0, 10);
const dayOf = (date) => new Date(`${date}T12:00:00Z`).getUTCDay();
const clean = (value) => typeof value === 'string' ? value.trim() : value;

function entryDto(row) {
  return { id: row.id, sectionId: row.section_id, dayOfWeek: row.day_of_week, day: days[row.day_of_week], startTime: row.start_time, endTime: row.end_time, subjectCode: row.subject_code, subjectName: row.subject_name, lecturerId: row.lecturer_id, lecturerName: row.lecturer_name ?? null, room: row.room, entryType: row.entry_type, displayLabel: row.display_label, status: row.status, updatedAt: row.updated_at };
}
function overrideDto(row) {
  return { id: row.id, sectionId: row.section_id, baseEntryId: row.base_entry_id, date: row.override_date, changeKind: row.change_kind, startTime: row.start_time, endTime: row.end_time, subjectCode: row.subject_code, subjectName: row.subject_name, lecturerId: row.lecturer_id, lecturerName: row.lecturer_name ?? null, room: row.room, entryType: row.entry_type, note: row.note, status: row.status, original: parse(row.original_snapshot), createdBy: row.created_by_name, createdByRole: row.created_by_role, updatedAt: row.updated_at, publishedAt: row.published_at, revertedAt: row.reverted_at };
}

export function createTimetableService(db) {
  const sectionById = db.prepare('SELECT * FROM timetable_sections WHERE id=? AND status=\'ACTIVE\'');
  const userById = db.prepare('SELECT id,name,role,college_id,status FROM users WHERE id=?');
  const entryById = db.prepare(`SELECT e.*,u.name lecturer_name FROM timetable_entries e LEFT JOIN users u ON u.id=e.lecturer_id WHERE e.id=?`);
  const overrideById = db.prepare(`SELECT o.*,u.name lecturer_name,c.name created_by_name,c.role created_by_role FROM timetable_overrides o LEFT JOIN users u ON u.id=o.lecturer_id JOIN users c ON c.id=o.created_by WHERE o.id=?`);

  function accessibleSections(session) {
    const user = session.user; if (!user.college?.id) return [];
    if (user.role === Roles.COLLEGE_ADMIN) return db.prepare("SELECT * FROM timetable_sections WHERE college_id=? AND status='ACTIVE' ORDER BY semester,name").all(user.college.id);
    if (user.role === Roles.HOD) return db.prepare(`SELECT DISTINCT s.* FROM timetable_sections s JOIN timetable_user_scopes x ON x.department_id=s.department_id AND x.user_id=? WHERE s.college_id=? AND s.status='ACTIVE' ORDER BY s.semester,s.name`).all(user.id,user.college.id);
    if (user.role === Roles.STUDENT) return db.prepare(`SELECT DISTINCT s.* FROM timetable_sections s JOIN timetable_user_scopes x ON x.section_id=s.id WHERE x.user_id=? AND s.college_id=? AND s.status='ACTIVE' ORDER BY s.name`).all(user.id,user.college.id);
    if (user.role === Roles.LECTURER) return db.prepare(`SELECT DISTINCT s.* FROM timetable_sections s LEFT JOIN timetable_user_scopes x ON x.section_id=s.id AND x.user_id=? LEFT JOIN timetable_entries e ON e.section_id=s.id AND e.lecturer_id=? AND e.status='ACTIVE' WHERE s.college_id=? AND s.status='ACTIVE' AND (x.user_id IS NOT NULL OR e.id IS NOT NULL) ORDER BY s.name`).all(user.id,user.id,user.college.id);
    return [];
  }
  function scopeFor(session, sectionId) { return db.prepare('SELECT * FROM timetable_user_scopes WHERE user_id=? AND section_id=?').get(session.user.id,sectionId); }
  function assertSection(session, sectionId) { const section=sectionById.get(sectionId); if(!section||!accessibleSections(session).some(item=>item.id===sectionId)) throw new AppError(403,'TIMETABLE_SCOPE_DENIED','This timetable is outside your authorized scope.'); return section; }
  function canManage(session, section) { if(session.user.role===Roles.HOD)return Boolean(db.prepare('SELECT 1 FROM timetable_user_scopes WHERE user_id=? AND department_id=?').get(session.user.id,section.department_id)); if(session.user.role===Roles.LECTURER)return Boolean(scopeFor(session,section.id)?.is_class_teacher); return false; }
  function requireManage(session, sectionId) { const section=assertSection(session,sectionId); if(!canManage(session,section))throw new AppError(403,'TIMETABLE_READ_ONLY','This account has read-only timetable access.'); return section; }
  function validateTime(start,end){if(!/^\d{2}:\d{2}$/.test(start??'')||!/^\d{2}:\d{2}$/.test(end??'')||start>=end)throw new AppError(400,'INVALID_TIME_RANGE','Choose a valid start and end time.');}
  function validateLecturer(section, lecturerId){if(!lecturerId)return;const lecturer=userById.get(lecturerId);if(!lecturer||lecturer.college_id!==section.college_id||!['HOD','LECTURER'].includes(lecturer.role)||lecturer.status!=='ACTIVE')throw new AppError(400,'INVALID_LECTURER_ASSIGNMENT','Choose an active lecturer from this college.');}
  function conflictFor(input, ignoreEntryId, date) {
    const day = date ? dayOf(date) : Number(input.dayOfWeek); const params=[day,input.startTime,input.endTime,ignoreEntryId??''];
    const rows=db.prepare(`SELECT e.*,s.name section_name,u.name lecturer_name FROM timetable_entries e JOIN timetable_sections s ON s.id=e.section_id LEFT JOIN users u ON u.id=e.lecturer_id WHERE e.status='ACTIVE' AND e.day_of_week=? AND e.start_time<? AND ?<e.end_time AND e.id<>?`).all(...params);
    const conflict=rows.find(row=>row.section_id===input.sectionId||(input.lecturerId&&row.lecturer_id===input.lecturerId)||(input.room&&row.room?.toLowerCase()===input.room.toLowerCase()));
    if(!conflict)return null; const reason=conflict.section_id===input.sectionId?`${conflict.section_name} already has ${conflict.subject_name} at ${conflict.start_time}.`:conflict.lecturer_id===input.lecturerId?`${conflict.lecturer_name} is already scheduled for ${conflict.section_name} at ${conflict.start_time}.`:`${conflict.room} is already occupied by ${conflict.section_name} at ${conflict.start_time}.`;return {code:'TIMETABLE_CONFLICT',message:reason,entryId:conflict.id};
  }
  function recordHistory(session, sectionId, entityType, entityId, action, oldValue, newValue) { db.prepare('INSERT INTO timetable_history (id,section_id,entity_type,entity_id,action,old_value,new_value,changed_by,changed_by_role,changed_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),sectionId,entityType,entityId,action,oldValue?JSON.stringify(oldValue):null,newValue?JSON.stringify(newValue):null,session.user.id,session.user.role,new Date().toISOString()); }
  function entryInput(raw){const value={sectionId:clean(raw.sectionId),dayOfWeek:Number(raw.dayOfWeek),startTime:clean(raw.startTime),endTime:clean(raw.endTime),subjectCode:clean(raw.subjectCode)||null,subjectName:clean(raw.subjectName),lecturerId:clean(raw.lecturerId)||null,room:clean(raw.room)||null,entryType:String(raw.entryType??'CLASS').toUpperCase(),displayLabel:clean(raw.displayLabel)||null};if(!value.sectionId||!Number.isInteger(value.dayOfWeek)||value.dayOfWeek<0||value.dayOfWeek>6||!value.subjectName||!entryTypes.has(value.entryType))throw new AppError(400,'INVALID_TIMETABLE_ENTRY','Complete the class, day, subject, time, and entry type.');validateTime(value.startTime,value.endTime);return value;}
  function expireOverrides(){db.prepare("UPDATE timetable_overrides SET status='EXPIRED',updated_at=? WHERE status='PUBLISHED' AND override_date<?").run(new Date().toISOString(),isoToday());}

  function view(session, query={}) {
    expireOverrides(); const sections=accessibleSections(session); if(!sections.length)return {sections:[],slots:[],entries:[],overrides:[],effectiveEntries:[],lecturers:[],history:[],notifications:[],permissions:{manageOfficial:false,manageOverrides:false}};
    const requested=query.sectionId; const section=sections.find(item=>item.id===requested)??sections[0]; const date=query.date??isoToday();
    const slots=db.prepare('SELECT id,label,start_time startTime,end_time endTime,slot_order slotOrder,kind FROM timetable_slots WHERE college_id=? AND department_id=? ORDER BY slot_order').all(section.college_id,section.department_id);
    let entries=db.prepare(`SELECT e.*,u.name lecturer_name FROM timetable_entries e LEFT JOIN users u ON u.id=e.lecturer_id WHERE e.section_id=? AND e.status='ACTIVE' ORDER BY e.day_of_week,e.start_time`).all(section.id).map(entryDto);
    if(session.user.role===Roles.LECTURER&&!scopeFor(session,section.id)?.is_class_teacher)entries=entries.filter(item=>item.lecturerId===session.user.id);
    const overrides=db.prepare(`SELECT o.*,u.name lecturer_name,c.name created_by_name,c.role created_by_role FROM timetable_overrides o LEFT JOIN users u ON u.id=o.lecturer_id JOIN users c ON c.id=o.created_by WHERE o.section_id=? AND (o.status='PUBLISHED' OR o.created_by=?) ORDER BY o.override_date DESC,o.updated_at DESC`).all(section.id,session.user.id).map(overrideDto);
    const baseForDay=entries.filter(item=>item.dayOfWeek===dayOf(date)); const active=overrides.filter(item=>item.date===date&&item.status==='PUBLISHED'); const effective=[];
    for(const base of baseForDay){const change=active.find(item=>item.baseEntryId===base.id);if(!change)effective.push({...base,date,presentationStatus:'Normal'});else if(change.changeKind==='CANCELLED')effective.push({...base,date,presentationStatus:'Cancelled',overrideId:change.id,note:change.note});else effective.push({...base,date,startTime:change.startTime??base.startTime,endTime:change.endTime??base.endTime,subjectCode:change.subjectCode??base.subjectCode,subjectName:change.subjectName??base.subjectName,lecturerId:change.lecturerId??base.lecturerId,lecturerName:change.lecturerName??base.lecturerName,room:change.room??base.room,entryType:change.entryType??base.entryType,presentationStatus:change.lecturerId&&change.lecturerId!==base.lecturerId?'Substitution':'Changed',overrideId:change.id,note:change.note});}
    active.filter(item=>!item.baseEntryId).forEach(change=>effective.push({id:`override:${change.id}`,sectionId:change.sectionId,date,startTime:change.startTime,endTime:change.endTime,subjectCode:change.subjectCode,subjectName:change.subjectName,lecturerId:change.lecturerId,lecturerName:change.lecturerName,room:change.room,entryType:change.entryType??'SPECIAL',presentationStatus:'Special',overrideId:change.id,note:change.note}));effective.sort((a,b)=>(a.startTime??'').localeCompare(b.startTime??''));
    const manage=canManage(session,section); const history=manage?db.prepare(`SELECT h.*,u.name changed_by_name FROM timetable_history h JOIN users u ON u.id=h.changed_by WHERE h.section_id=? ORDER BY h.changed_at DESC LIMIT 100`).all(section.id).map(row=>({id:row.id,entityType:row.entity_type,entityId:row.entity_id,action:row.action,oldValue:parse(row.old_value),newValue:parse(row.new_value),changedBy:row.changed_by_name,role:row.changed_by_role,at:row.changed_at})):[];
    const lecturers=db.prepare("SELECT id,name,role FROM users WHERE college_id=? AND status='ACTIVE' AND role IN ('HOD','LECTURER') ORDER BY name").all(section.college_id);
    const notifications=db.prepare(`SELECT e.id,e.title,e.message,e.created_at createdAt,r.read_at readAt FROM notification_events e JOIN notification_recipients r ON r.event_id=e.id WHERE r.user_id=? ORDER BY e.created_at DESC LIMIT 50`).all(session.user.id);
    return {date,sections:sections.map(item=>({id:item.id,departmentId:item.department_id,academicYear:item.academic_year,semester:item.semester,batch:item.batch_name,name:item.name,room:item.default_room})),selectedSectionId:section.id,slots,entries,overrides,effectiveEntries:effective,lecturers,history,notifications,permissions:{manageOfficial:manage,manageOverrides:manage,isClassTeacher:Boolean(scopeFor(session,section.id)?.is_class_teacher)}};
  }
  function saveEntry(session, raw, id) { const input=entryInput(raw);const section=requireManage(session,input.sectionId);validateLecturer(section,input.lecturerId);const conflict=conflictFor(input,id);if(conflict)throw new AppError(409,conflict.code,conflict.message,conflict);const now=new Date().toISOString();const existing=id?entryById.get(id):null;if(id&&(!existing||existing.section_id!==section.id))throw new AppError(404,'TIMETABLE_ENTRY_NOT_FOUND','Timetable entry not found.');const entryId=id??randomUUID();if(existing)db.prepare(`UPDATE timetable_entries SET day_of_week=?,start_time=?,end_time=?,subject_code=?,subject_name=?,lecturer_id=?,room=?,entry_type=?,display_label=?,updated_at=? WHERE id=?`).run(input.dayOfWeek,input.startTime,input.endTime,input.subjectCode,input.subjectName,input.lecturerId,input.room,input.entryType,input.displayLabel,now,id);else db.prepare(`INSERT INTO timetable_entries (id,section_id,day_of_week,start_time,end_time,subject_code,subject_name,lecturer_id,room,entry_type,display_label,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'ACTIVE',?,?,?)`).run(entryId,input.sectionId,input.dayOfWeek,input.startTime,input.endTime,input.subjectCode,input.subjectName,input.lecturerId,input.room,input.entryType,input.displayLabel,session.user.id,now,now);const saved=entryDto(entryById.get(entryId));recordHistory(session,section.id,'ENTRY',entryId,existing?'UPDATED':'CREATED',existing?entryDto(existing):null,saved);return saved; }
  function deactivateEntry(session,id){const existing=entryById.get(id);if(!existing)throw new AppError(404,'TIMETABLE_ENTRY_NOT_FOUND','Timetable entry not found.');const section=requireManage(session,existing.section_id);db.prepare("UPDATE timetable_entries SET status='INACTIVE',updated_at=? WHERE id=?").run(new Date().toISOString(),id);recordHistory(session,section.id,'ENTRY',id,'DEACTIVATED',entryDto(existing),null);return {id,deactivated:true};}
  function overrideInput(raw){const value={sectionId:clean(raw.sectionId),baseEntryId:clean(raw.baseEntryId)||null,date:clean(raw.date),changeKind:String(raw.changeKind??'CHANGE').toUpperCase(),startTime:clean(raw.startTime)||null,endTime:clean(raw.endTime)||null,subjectCode:clean(raw.subjectCode)||null,subjectName:clean(raw.subjectName)||null,lecturerId:clean(raw.lecturerId)||null,room:clean(raw.room)||null,entryType:clean(raw.entryType)||null,note:clean(raw.note)||null};if(!value.sectionId||!/^\d{4}-\d{2}-\d{2}$/.test(value.date??'')||!changeKinds.has(value.changeKind))throw new AppError(400,'INVALID_OVERRIDE','Choose an affected class, date, and change type.');if(value.changeKind!=='CANCELLED'&&value.startTime&&value.endTime)validateTime(value.startTime,value.endTime);return value;}
  function saveOverride(session,raw,id){const input=overrideInput(raw);const section=requireManage(session,input.sectionId);const base=input.baseEntryId?entryById.get(input.baseEntryId):null;if(input.baseEntryId&&(!base||base.section_id!==section.id))throw new AppError(400,'INVALID_BASE_ENTRY','Choose an entry from the affected class.');if(!base&&input.changeKind!=='SPECIAL'&&input.changeKind!=='RESCHEDULED')throw new AppError(400,'BASE_ENTRY_REQUIRED','Choose the original timetable entry.');validateLecturer(section,input.lecturerId);if(!base&&(!input.subjectName||!input.startTime||!input.endTime))throw new AppError(400,'SPECIAL_CLASS_INCOMPLETE','Special classes require subject and time.');const existing=id?overrideById.get(id):null;if(existing&&existing.status!=='DRAFT')throw new AppError(409,'OVERRIDE_NOT_EDITABLE','Only draft changes can be edited.');const original=base?entryDto(base):null;const now=new Date().toISOString(),overrideId=id??randomUUID();if(existing)db.prepare(`UPDATE timetable_overrides SET base_entry_id=?,override_date=?,change_kind=?,start_time=?,end_time=?,subject_code=?,subject_name=?,lecturer_id=?,room=?,entry_type=?,note=?,updated_at=? WHERE id=?`).run(input.baseEntryId,input.date,input.changeKind,input.startTime,input.endTime,input.subjectCode,input.subjectName,input.lecturerId,input.room,input.entryType,input.note,now,id);else db.prepare(`INSERT INTO timetable_overrides (id,section_id,base_entry_id,override_date,change_kind,start_time,end_time,subject_code,subject_name,lecturer_id,room,entry_type,note,status,original_snapshot,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'DRAFT',?,?,?,?)`).run(overrideId,input.sectionId,input.baseEntryId,input.date,input.changeKind,input.startTime,input.endTime,input.subjectCode,input.subjectName,input.lecturerId,input.room,input.entryType,input.note,original?JSON.stringify(original):null,session.user.id,now,now);recordHistory(session,section.id,'OVERRIDE',overrideId,existing?'DRAFT_UPDATED':'DRAFT_CREATED',existing?overrideDto(existing):null,overrideDto(overrideById.get(overrideId)));return overrideDto(overrideById.get(overrideId));}
  function effectiveChange(row){const original=parse(row.original_snapshot);return {sectionId:row.section_id,date:row.override_date,startTime:row.start_time??original?.startTime,endTime:row.end_time??original?.endTime,subjectCode:row.subject_code??original?.subjectCode,subjectName:row.subject_name??original?.subjectName,lecturerId:row.lecturer_id??original?.lecturerId,room:row.room??original?.room,entryType:row.entry_type??original?.entryType,changeKind:row.change_kind};}
  function meaningful(row){const original=parse(row.original_snapshot);if(!original)return true;if(row.change_kind==='CANCELLED')return true;const next=effectiveChange(row);return ['startTime','endTime','subjectCode','subjectName','lecturerId','room','entryType'].some(key=>(next[key]??null)!==(original[key]??null));}
  function publishNotifications(session,row,section){if(!meaningful(row))return 0;const original=parse(row.original_snapshot);const next=effectiveChange(row);const recipients=new Map();if(section.source_class_id)db.prepare('SELECT student_id FROM class_enrollments WHERE class_id=?').all(section.source_class_id).forEach(item=>recipients.set(item.student_id,'STUDENT'));if(original?.lecturerId)recipients.set(original.lecturerId,'ORIGINAL_LECTURER');if(next.lecturerId)recipients.set(next.lecturerId,'REPLACEMENT_LECTURER');let count=0;for(const[userId,kind]of recipients){const user=userById.get(userId);if(!user)continue;const timeChange=original?`${original.startTime} to ${next.startTime}`:next.startTime;const title=row.change_kind==='CANCELLED'?'Class cancelled':row.change_kind==='SPECIAL'||row.change_kind==='RESCHEDULED'?'Special class scheduled':'Timetable changed';const message=kind==='REPLACEMENT_LECTURER'&&userId!==original?.lecturerId?`You have been assigned ${next.subjectName} for ${section.name} at ${next.startTime} on ${row.override_date}.`:kind==='ORIGINAL_LECTURER'&&next.lecturerId!==original?.lecturerId?`Your ${original?.subjectName} class for ${section.name} has been reassigned.`:`${next.subjectName} for ${section.name} changed ${timeChange}. ${next.room?`Room ${next.room}.`:''}`;const eventId=randomUUID(),createdAt=new Date().toISOString();db.prepare('INSERT INTO notification_events (id,category,title,message,section_id,source_id,created_by,created_at) VALUES (?,?,?,?,?,?,?,?)').run(eventId,'TIMETABLE',title,message.trim(),section.id,row.id,session.user.id,createdAt);db.prepare('INSERT OR IGNORE INTO notification_recipients (event_id,user_id) VALUES (?,?)').run(eventId,userId);const tokens=db.prepare('SELECT id FROM device_tokens WHERE user_id=? AND active=1').all(userId);if(tokens.length)tokens.forEach(token=>db.prepare("INSERT INTO notification_deliveries (id,event_id,user_id,device_token_id,status) VALUES (?,?,?,?,'QUEUED')").run(randomUUID(),eventId,userId,token.id));else db.prepare("INSERT INTO notification_deliveries (id,event_id,user_id,status) VALUES (?,?,?,'SKIPPED')").run(randomUUID(),eventId,userId);count++;}return count;}
  function publishOverride(session,id){const row=overrideById.get(id);if(!row)throw new AppError(404,'OVERRIDE_NOT_FOUND','Temporary change not found.');const section=requireManage(session,row.section_id);if(row.status!=='DRAFT')throw new AppError(409,'OVERRIDE_NOT_DRAFT','Only draft changes can be published.');const next=effectiveChange(row);if(row.change_kind!=='CANCELLED'){validateTime(next.startTime,next.endTime);const conflict=conflictFor(next,row.base_entry_id,row.override_date);if(conflict)throw new AppError(409,conflict.code,conflict.message,conflict);}const now=new Date().toISOString();db.prepare("UPDATE timetable_overrides SET status='PUBLISHED',published_at=?,updated_at=? WHERE id=?").run(now,now,id);const notifications=publishNotifications(session,row,section);const published=overrideDto(overrideById.get(id));recordHistory(session,section.id,'OVERRIDE',id,'PUBLISHED',overrideDto(row),published);return {...published,notificationCount:notifications};}
  function revertOverride(session,id){const row=overrideById.get(id);if(!row)throw new AppError(404,'OVERRIDE_NOT_FOUND','Temporary change not found.');const section=requireManage(session,row.section_id);if(row.status!=='PUBLISHED')throw new AppError(409,'OVERRIDE_NOT_ACTIVE','Only published changes can be reverted.');const now=new Date().toISOString();db.prepare("UPDATE timetable_overrides SET status='REVERTED',reverted_at=?,updated_at=? WHERE id=?").run(now,now,id);const reverted=overrideDto(overrideById.get(id));recordHistory(session,section.id,'OVERRIDE',id,'REVERTED',overrideDto(row),reverted);if(meaningful(row)){const copy={...row,id:`${row.id}:revert`,change_kind:'CHANGE',start_time:parse(row.original_snapshot)?.startTime,subject_name:parse(row.original_snapshot)?.subjectName,lecturer_id:parse(row.original_snapshot)?.lecturerId,room:parse(row.original_snapshot)?.room};publishNotifications(session,copy,section);}return reverted;}
  function cancelOverride(session,id){const row=overrideById.get(id);if(!row)throw new AppError(404,'OVERRIDE_NOT_FOUND','Temporary change not found.');const section=requireManage(session,row.section_id);if(row.status!=='DRAFT')throw new AppError(409,'OVERRIDE_NOT_DRAFT','Only draft changes can be cancelled.');const now=new Date().toISOString();db.prepare("UPDATE timetable_overrides SET status='CANCELLED',updated_at=? WHERE id=?").run(now,id);const cancelled=overrideDto(overrideById.get(id));recordHistory(session,section.id,'OVERRIDE',id,'CANCELLED',overrideDto(row),cancelled);return cancelled;}
  function registerDevice(session,input){const token=clean(input.token),platform=clean(input.platform)||'unknown';if(!token)throw new AppError(400,'DEVICE_TOKEN_REQUIRED','Device token is required.');const now=new Date().toISOString();db.prepare(`INSERT INTO device_tokens (id,user_id,token,platform,active,created_at,updated_at) VALUES (?,?,?,?,1,?,?) ON CONFLICT(token) DO UPDATE SET user_id=excluded.user_id,platform=excluded.platform,active=1,updated_at=excluded.updated_at`).run(randomUUID(),session.user.id,token,platform,now,now);return {registered:true};}
  return {view,saveEntry,deactivateEntry,saveOverride,publishOverride,revertOverride,cancelOverride,registerDevice};
}
