import { useState } from 'react';
import { router, type Href } from 'expo-router';
import { Button } from '@/design-system/components/core';
import { AlertBanner, Confirmation } from '@/design-system/components/feedback';
import { TextField } from '@/design-system/components/forms';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { OptionPicker } from '@/hod/management-components';
import { useHodOperations } from '@/hod/operations-provider';

export default function CreateDepartmentNotification(){const operations=useHodOperations();const [title,setTitle]=useState('');const [message,setMessage]=useState('');const [category,setCategory]=useState('Academic');const [priority,setPriority]=useState<'Normal'|'High'>('Normal');const [audience,setAudience]=useState('Entire department');const [confirm,setConfirm]=useState(false);const valid=title.trim()&&message.trim()&&audience;const save=(send:boolean)=>{const item=operations.createNotification({title:title.trim(),message:message.trim(),category,priority,audience},send);router.replace(`/hod/management/notifications/${item.id}` as Href);};return <HodShell activeKey="department" title="Create notification" subtitle="Department audience only" back backFallback="/hod/management/notifications"><PageContainer width="compact" fixedActions={<Button label="Review & send" disabled={!valid} onPress={()=>setConfirm(true)}/>}><AlertBanner title="Department scope" message="College-wide and administrative audiences are not available to this HOD account." tone="info"/><TextField label="Title" required value={title} onChangeText={setTitle}/><TextField label="Message" required value={message} onChangeText={setMessage} multiline numberOfLines={5}/><OptionPicker label="Category" value={category} options={['Academic','Attendance','Operations','Important'].map((value)=>({value,label:value}))} onChange={setCategory}/><OptionPicker label="Priority" value={priority} options={[{value:'Normal',label:'Normal'},{value:'High',label:'High'}]} onChange={(value)=>setPriority(value as typeof priority)}/><OptionPicker label="Audience" value={audience} options={['Entire department','Semester 7','Semester 5','Batch 2024','Batch 2025','CSE 2024 A','CSE 2025 B','Lecturers','Students'].map((value)=>({value,label:value}))} onChange={setAudience}/><Button label="Save draft" variant="secondary" disabled={!valid} onPress={()=>save(false)}/><Confirmation visible={confirm} title="Send department notification?" message={`${title} will be sent to ${audience}. This audience does not include another department or college-wide recipients.`} confirmLabel="Send notification" onDismiss={()=>setConfirm(false)} onConfirm={()=>save(true)}/></PageContainer></HodShell>;}
