import { useMemo, useState } from 'react';
import { router, type Href, useLocalSearchParams } from 'expo-router';
import { StateView } from '@/design-system/components/states';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { FilterChips, ManagementHeader, ManagementRow, ManagementSearch, SummaryStrip } from '@/hod/management-components';
import { useHodManagement } from '@/hod/management-provider';

export default function StudentsManagement() {
  const data = useHodManagement(); const params = useLocalSearchParams<{ filter?: string }>(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'attention' | 'inactive'>(params.filter === 'attention' ? 'attention' : 'all');
  const students = useMemo(() => data.students.filter((item) => { const matches = `${item.name} ${item.usn} ${item.email}`.toLowerCase().includes(query.toLowerCase()); return matches && (filter === 'all' || filter === 'attention' && item.attendance < 75 || filter === 'inactive' && item.status === 'Inactive'); }), [data.students, filter, query]);
  return <HodShell activeKey="department" title="Students" subtitle={`${data.students.length} department students`} back backFallback="/hod/management"><PageContainer width="full"><ManagementHeader title="Department students" description="Manage identities and academic placement within Computer Science & Engineering." action="Add student" onAction={() => router.push('/hod/management/students/new' as Href)} /><SummaryStrip items={[{ value: data.students.length, label: 'Total' }, { value: data.students.filter((item) => item.status === 'Active').length, label: 'Active' }, { value: data.students.filter((item) => item.attendance < 75).length, label: 'Need attention' }]} /><ManagementSearch value={query} onChangeText={setQuery} placeholder="Search name, USN, or email" /><FilterChips value={filter} onChange={setFilter} options={[{ value: 'all', label: 'All' }, { value: 'attention', label: 'Needs attention' }, { value: 'inactive', label: 'Inactive' }]} />{students.length ? students.map((student) => { const semester = data.semesters.find((item) => item.id === student.semesterId); const batch = data.batches.find((item) => item.id === student.batchId); const section = data.sections.find((item) => item.id === student.sectionId); return <ManagementRow key={student.id} title={student.name} detail={`${student.usn} · ${semester?.name} · ${section?.name}`} meta={`${batch?.name} · ${student.attendance}% attendance`} status={student.status} onPress={() => router.push(`/hod/management/students/${student.id}` as Href)} />; }) : <StateView state="empty" title="No students found" message={query ? 'Try another search or filter.' : 'No students have been added yet.'} />}</PageContainer></HodShell>;
}
