import React,{createContext,useEffect,useState} from 'react';
import {useAuth} from '@/auth/auth-provider';
import {AuthApiError} from '@/auth/types';
import {timetableClient} from './client';
import type {TimetableData,TimetableEntryInput,TimetableOverrideInput} from './types';
const localDate=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
type Value={data?:TimetableData;loading:boolean;error?:AuthApiError;date:string;sectionId?:string;refresh:(date?:string,sectionId?:string)=>Promise<void>;selectDate:(date:string)=>Promise<void>;selectSection:(id:string)=>Promise<void>;saveEntry:(input:TimetableEntryInput,id?:string)=>Promise<void>;deactivateEntry:(id:string)=>Promise<void>;saveOverride:(input:TimetableOverrideInput,id?:string)=>Promise<string>;publishOverride:(id:string)=>Promise<void>;revertOverride:(id:string)=>Promise<void>;cancelOverride:(id:string)=>Promise<void>};
const Context=createContext<Value|null>(null);
export function TimetableProvider({children}:React.PropsWithChildren){const{session}=useAuth();const[data,setData]=useState<TimetableData>();const[loading,setLoading]=useState(true);const[error,setError]=useState<AuthApiError>();const[date,setDate]=useState(localDate);const[sectionId,setSectionId]=useState<string>();
 const refresh=async(nextDate=date,nextSection=sectionId)=>{if(!session?.token)return;setLoading(true);setError(undefined);try{const value=await timetableClient.fetch(session.token,nextDate,nextSection);setData(value);setDate(nextDate);setSectionId(value.selectedSectionId);}catch(reason){setError(reason instanceof AuthApiError?reason:new AuthApiError('TIMETABLE_ERROR','Unable to load timetable.'));}finally{setLoading(false);}};
 useEffect(()=>{let active=true;if(session?.token)void timetableClient.fetch(session.token,localDate()).then(value=>{if(active){setData(value);setDate(value.date??localDate());setSectionId(value.selectedSectionId);setError(undefined);}}).catch(reason=>{if(active)setError(reason instanceof AuthApiError?reason:new AuthApiError('TIMETABLE_ERROR','Unable to load timetable.'));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[session?.token]);
 const requireToken=()=>{if(!session?.token)throw new AuthApiError('UNAUTHORIZED','Authentication is required.');return session.token;};
 const saveEntry=async(input:TimetableEntryInput,id?:string)=>{await timetableClient.saveEntry(requireToken(),input,id);await refresh(date,input.sectionId);};const deactivateEntry=async(id:string)=>{await timetableClient.deactivateEntry(requireToken(),id);await refresh();};const saveOverride=async(input:TimetableOverrideInput,id?:string)=>{const saved=await timetableClient.saveOverride(requireToken(),input,id);await refresh(input.date,input.sectionId);return saved.id;};const publishOverride=async(id:string)=>{await timetableClient.publishOverride(requireToken(),id);await refresh();};const revertOverride=async(id:string)=>{await timetableClient.revertOverride(requireToken(),id);await refresh();};const cancelOverride=async(id:string)=>{await timetableClient.cancelOverride(requireToken(),id);await refresh();};
 const value:Value={data,loading,error,date,sectionId,refresh,selectDate:async(next)=>refresh(next,sectionId),selectSection:async(next)=>refresh(date,next),saveEntry,deactivateEntry,saveOverride,publishOverride,revertOverride,cancelOverride};return <Context value={value}>{children}</Context>;}
export function useTimetable(){const value=React.use(Context);if(!value)throw new Error('useTimetable must be used within TimetableProvider');return value;}
