import { useMemo, useState } from 'react';
import { router, type Href } from 'expo-router';
import { Pressable, Text, View } from 'react-native';
import { Confirmation } from '@/design-system/components/feedback';
import { radii, sizing, spacing } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { HodShell } from '@/hod/components';
import { FilterChips, ManagementHeader, ManagementRow, RelationshipSection, SummaryStrip } from '@/hod/management-components';
import { BulkActionBar } from '@/hod/operations-components';
import { useHodManagement } from '@/hod/management-provider';
import { useHodOperations } from '@/hod/operations-provider';

export default function AttendanceIssues() {
  const { colors } = useRollCallTheme(); const data = useHodManagement(); const operations=useHodOperations(); const [filter,setFilter]=useState<'open'|'history'>('open'); const [selected,setSelected]=useState<string[]>([]); const [confirm,setConfirm]=useState(false); const rows=useMemo(()=>operations.issues.filter((item)=>filter==='open'?!['Resolved'].includes(item.status):['Approved','Rejected','Resolved'].includes(item.status)),[filter,operations.issues]);
  return <HodShell activeKey="department" title="Attendance issues" subtitle="Correction review" back backFallback="/hod/management/attendance"><PageContainer width="full"><ManagementHeader title="Issue inbox" description="Review attendance correction requests with student and session context." /><SummaryStrip items={[{value:operations.issues.filter((item)=>item.status==='Submitted').length,label:'Submitted'},{value:operations.issues.filter((item)=>item.status==='Under Review').length,label:'Under review'},{value:operations.issues.filter((item)=>['Approved','Rejected'].includes(item.status)).length,label:'Decided'}]} /><FilterChips value={filter} onChange={(value)=>{setFilter(value);setSelected([]);}} options={[{value:'open',label:'Open issues'},{value:'history',label:'Correction history'}]} /><BulkActionBar selected={selected.length} total={rows.length} onSelectAll={()=>setSelected(rows.map((item)=>item.id))} onClear={()=>setSelected([])} action="Mark resolved" onAction={()=>setConfirm(true)} /><RelationshipSection title={filter==='open'?'Needs review':'Decision history'}>{rows.map((issue)=>{const student=data.students.find((item)=>item.id===issue.studentId);const subject=data.subjects.find((item)=>item.id===issue.subjectId);const checked=selected.includes(issue.id);return <View key={issue.id} style={{flexDirection:'row',alignItems:'center',gap:spacing.sm}}>{filter==='history'?<Pressable accessibilityRole="checkbox" accessibilityState={{checked}} onPress={()=>setSelected((current)=>checked?current.filter((id)=>id!==issue.id):[...current,issue.id])} style={{width:sizing.touchTarget,height:sizing.touchTarget,alignItems:'center',justifyContent:'center'}}><View style={{width:22,height:22,borderRadius:radii.sm,borderWidth:2,borderColor:checked?colors.primary:colors.border,backgroundColor:checked?colors.primary:'transparent'}}>{checked?<Text style={{color:colors.textInverse}}>✓</Text>:null}</View></Pressable>:null}<View style={{flex:1}}><ManagementRow title={student?.name??'Student'} detail={`${subject?.name} · ${issue.issueType}`} meta={`${issue.existingStatus} → ${issue.requestedStatus} · ${new Date(issue.submittedAt).toLocaleDateString()}`} status={issue.status==='Submitted'||issue.status==='Under Review'?'Pending':issue.status==='Approved'?'Assigned':'Inactive'} onPress={()=>router.push(`/hod/management/issues/${issue.id}` as Href)} /></View></View>;})}</RelationshipSection><Confirmation visible={confirm} title="Mark selected decisions resolved?" message="Decision history remains available. Only completed decisions can be resolved." confirmLabel="Mark resolved" onDismiss={()=>setConfirm(false)} onConfirm={()=>{operations.resolveIssues(selected);setSelected([]);setConfirm(false);}} /></PageContainer></HodShell>;
}
