import React, { createContext, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, type Href, useNavigation } from 'expo-router';
import { useAuth } from '@/auth/auth-provider';
import { Avatar, Card, IconButton } from '@/design-system/components/core';
import { radii, sizing, spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { useResponsive } from '@/design-system/use-responsive';
import { AppShell, CompactHeader } from '@/shell/app-shell';
import { AdaptiveUtilityMenu, UtilityMenuRow } from '@/lecturer/utility-components';
import { Dialog } from '@/design-system/components/feedback';
import type { ApplicationStatus, CollegeApplication, CollegeWorkspace, PaymentStatus, Plan, Subscription } from './platform-provider';
import { useSuperAdminOperations } from './operations-provider';

const navigation={primary:[{key:'dashboard',label:'Dashboard',href:'/super-admin'},{key:'applications',label:'Applications',href:'/super-admin/applications'},{key:'colleges',label:'Colleges',href:'/super-admin/colleges'},{key:'payments',label:'Payments',href:'/super-admin/payments'},{key:'health',label:'Health',href:'/super-admin/health'}],secondary:[{key:'support',label:'Support',href:'/super-admin/support'},{key:'activity',label:'Activity',href:'/super-admin/activity'},{key:'search',label:'Search',href:'/super-admin/search'},{key:'settings',label:'Settings',href:'/super-admin/settings'}]} as const;
type Utilities={quick:boolean;account:boolean;setQuick:(v:boolean)=>void;setAccount:(v:boolean)=>void};const UtilityContext=createContext<Utilities|null>(null);
export function SuperAdminUtilityProvider({children}:React.PropsWithChildren){const[quick,setQuick]=useState(false);const[account,setAccount]=useState(false);return <UtilityContext value={{quick,account,setQuick,setAccount}}>{children}</UtilityContext>}
function useUtilities(){const value=React.use(UtilityContext);if(!value)throw new Error('SuperAdminUtilityProvider missing');return value;}
export function SuperAdminShell({activeKey,title,subtitle,back=false,children}:{activeKey:string;title:string;subtitle?:string;back?:boolean;children:React.ReactNode}){const{colors}=useRollCallTheme();const{session}=useAuth();const utilities=useUtilities();const nav=useNavigation();const trailing=<View style={{flexDirection:'row',alignItems:'center'}}><IconButton label="Search platform" onPress={()=>router.push('/super-admin/search' as Href)}><Ionicons name="search-outline" size={sizing.iconMd} color={colors.textSecondary}/></IconButton><IconButton label="Open quick actions" onPress={()=>utilities.setQuick(true)}><Ionicons name="add-circle-outline" size={sizing.iconLg} color={colors.primary}/></IconButton><Pressable accessibilityRole="button" accessibilityLabel="Open Super Admin account menu" onPress={()=>utilities.setAccount(true)} style={({pressed})=>({minHeight:sizing.touchTarget,borderRadius:radii.full,paddingHorizontal:spacing.xs,justifyContent:'center',opacity:pressed ? .7 : 1})}><Avatar name={session?.user.name??'Platform Owner'} size="small"/></Pressable></View>;return <AppShell navigation={navigation} activeKey={activeKey} role="super-admin" header={<CompactHeader title={title} subtitle={subtitle} backAction={back?()=>nav.canGoBack()?nav.goBack():router.replace('/super-admin' as Href):undefined} trailing={trailing}/>}>{children}</AppShell>}
export function SuperAdminOverlays(){const utilities=useUtilities();const{session,logout}=useAuth();const go=(href:string,type:'quick'|'account')=>{if(type==='quick')utilities.setQuick(false);else utilities.setAccount(false);router.push(href as Href)};return <><AdaptiveUtilityMenu visible={utilities.quick} title="Quick actions" onDismiss={()=>utilities.setQuick(false)}><UtilityMenuRow icon="clipboard-outline" title="Review Applications" onPress={()=>go('/super-admin/applications','quick')}/><UtilityMenuRow icon="business-outline" title="View Colleges" onPress={()=>go('/super-admin/colleges','quick')}/><UtilityMenuRow icon="card-outline" title="View Payments" onPress={()=>go('/super-admin/payments','quick')}/><UtilityMenuRow icon="pricetags-outline" title="Manage Plans" onPress={()=>go('/super-admin/plans','quick')}/></AdaptiveUtilityMenu><AdaptiveUtilityMenu visible={utilities.account} title="Platform account" onDismiss={()=>utilities.setAccount(false)}><UtilityMenuRow icon="person-circle-outline" title={session?.user.name??'Platform Owner'} detail={session?.user.loginIdentifier} onPress={()=>go('/super-admin/settings','account')}/><UtilityMenuRow icon="settings-outline" title="Settings" onPress={()=>go('/super-admin/settings','account')}/><UtilityMenuRow icon="log-out-outline" title="Sign out" destructive onPress={()=>{utilities.setAccount(false);void logout();}}/></AdaptiveUtilityMenu></>}
const tone=(status:string)=>['Active','Paid','Workspace Active','Approved for Payment'].includes(status)?'success':['New','Under Review','Contacted','Due Soon','Payment Pending','Changes Requested'].includes(status)?'warning':['Rejected','Failed','Overdue','Suspended','Payment Issue'].includes(status)?'error':'neutral';
function BusinessRow({title,detail,meta,status,onPress}:{title:string;detail:string;meta:string;status:string;onPress:()=>void}){const{colors}=useRollCallTheme();const{isCompact}=useResponsive();return <Pressable accessibilityRole="button" accessibilityLabel={`${title}, ${status}`} onPress={onPress} style={({pressed})=>({minHeight:isCompact?104:78,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.borderSubtle,flexDirection:'row',alignItems:'center',gap:spacing.md,opacity:pressed ? .68 : 1})}><View style={{flex:1,gap:spacing.xs}}><Text style={[typography.subheading,{color:colors.textPrimary}]}>{title}</Text><Text style={[typography.bodySmall,{color:colors.textSecondary}]}>{detail}</Text><Text style={[typography.caption,{color:colors.textMuted}]}>{meta}</Text></View><View style={{alignItems:'flex-end',gap:spacing.xs}}><Text style={[typography.caption,{color:tone(status)==='error'?colors.error:tone(status)==='warning'?colors.warning:tone(status)==='success'?colors.success:colors.textMuted}]}>{status}</Text><Ionicons name="chevron-forward" size={sizing.iconSm} color={colors.textMuted}/></View></Pressable>}
export function ApplicationRow({item}:{item:CollegeApplication}){const operations=useSuperAdminOperations();return <BusinessRow title={item.collegeName} detail={`${item.contactName} · ${item.plan}`} meta={`${item.billingCycle} · ${new Date(item.appliedAt).toLocaleDateString()}`} status={item.status} onPress={()=>{operations.recordView({key:`application:${item.id}`,type:'Application',title:item.collegeName,detail:item.status,href:`/super-admin/applications/${item.id}`});router.push(`/super-admin/applications/${item.id}` as Href);}}/>}
export function WorkspaceRow({item}:{item:CollegeWorkspace}){const operations=useSuperAdminOperations();return <BusinessRow title={item.name} detail={`${item.workspaceReference} · ${item.plan}`} meta={`${item.billingCycle} · Renews ${new Date(item.renewalDate).toLocaleDateString()}`} status={item.status} onPress={()=>{operations.recordView({key:`college:${item.id}`,type:'College',title:item.name,detail:item.status,href:`/super-admin/colleges/${item.id}`});router.push(`/super-admin/colleges/${item.id}` as Href);}}/>}
export function SubscriptionRow({item}:{item:Subscription}){const operations=useSuperAdminOperations();return <BusinessRow title={item.college} detail={`${item.plan} · ₹${item.amount.toLocaleString('en-IN')}`} meta={`${item.billingCycle} · Next ${new Date(item.nextDueDate).toLocaleDateString()}`} status={item.status} onPress={()=>{operations.recordView({key:`payment:${item.id}`,type:'Payment',title:item.college,detail:item.status,href:`/super-admin/payments/${item.id}`});router.push(`/super-admin/payments/${item.id}` as Href);}}/>}
export function PlanCard({item,onEdit,onToggle}:{item:Plan;onEdit:()=>void;onToggle:()=>void}){const{colors}=useRollCallTheme();const[confirm,setConfirm]=useState(false);return <> <Card><View style={{flexDirection:'row',alignItems:'flex-start',gap:spacing.md}}><View style={{flex:1,gap:spacing.xs}}><Text accessibilityRole="header" style={[typography.heading,{color:colors.textPrimary}]}>{item.name}</Text><Text style={[typography.bodySmall,{color:colors.textSecondary}]}>{item.description}</Text></View><Text style={[typography.label,{color:item.status==='Active'?colors.success:colors.textMuted}]}>{item.status}</Text></View><Text style={[typography.title,{color:colors.textPrimary}]}>₹{item.price.toLocaleString('en-IN')}<Text style={[typography.caption,{color:colors.textMuted}]}> / {item.billingCycle==='Monthly'?'month':'year'}</Text></Text><Text style={[typography.bodySmall,{color:colors.textSecondary}]}>{item.capacity.toLocaleString()} students · {item.features.join(' · ')}</Text><View style={{flexDirection:'row',gap:spacing.sm}}><Pressable accessibilityRole="button" onPress={onEdit}><Text style={[typography.label,{color:colors.primary}]}>Edit</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>item.status==='Active'?setConfirm(true):onToggle()}><Text style={[typography.label,{color:item.status==='Active'?colors.error:colors.success}]}>{item.status==='Active'?'Disable':'Activate'}</Text></Pressable></View></Card><Dialog visible={confirm} title="Disable plan" message="New subscriptions will no longer be able to choose this plan. Existing subscriptions keep their historical plan and price." confirmLabel="Disable plan" destructive onDismiss={()=>setConfirm(false)} onConfirm={()=>{onToggle();setConfirm(false);}}/></>}
export const statusTone=(status:ApplicationStatus|PaymentStatus|string)=>tone(status);
