import React, { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Badge, Button, IconButton } from '@/design-system/components/core';
import { TextField } from '@/design-system/components/forms';
import { radii, sizing, spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { RelationshipSection } from '@/hod/management-components';
import { useSuperAdminOperations, type QuickItem, type SavedFilter } from './operations-provider';

const badgeTone=(value:string):'success'|'warning'|'error'|'neutral'=>['Operational','Resolved','Active','Paid'].includes(value)?'success':['Degraded','New','Investigating','Monitoring','Open','In Progress','High','Due Soon'].includes(value)?'warning':['Down','Major','Critical','Failed','Overdue','Suspended'].includes(value)?'error':'neutral';
export function OperationalRow({title,detail,meta,status,onPress,selected,onSelect}:{title:string;detail:string;meta?:string;status?:string;onPress?:()=>void;selected?:boolean;onSelect?:()=>void}){const{colors}=useRollCallTheme();const body=<View style={{flexDirection:'row',alignItems:'center',gap:spacing.md}}>{onSelect?<Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected}} accessibilityLabel={`Select ${title}`} onPress={onSelect} style={{width:sizing.touchTarget,height:sizing.touchTarget,alignItems:'center',justifyContent:'center'}}><View style={{width:22,height:22,borderRadius:radii.sm,borderWidth:2,borderColor:selected?colors.primary:colors.border,backgroundColor:selected?colors.primary:'transparent',alignItems:'center',justifyContent:'center'}}>{selected?<Ionicons name="checkmark" size={16} color={colors.textInverse}/>:null}</View></Pressable>:null}<View style={{flex:1,gap:spacing.xs}}><Text style={[typography.subheading,{color:colors.textPrimary}]}>{title}</Text><Text style={[typography.bodySmall,{color:colors.textSecondary}]}>{detail}</Text>{meta?<Text style={[typography.caption,{color:colors.textMuted}]}>{meta}</Text>:null}</View>{status?<Badge label={status} tone={badgeTone(status)}/>:null}{onPress?<Ionicons name="chevron-forward" size={sizing.iconSm} color={colors.textMuted}/>:null}</View>;return onPress?<Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>({minHeight:80,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.borderSubtle,opacity:pressed ? .68 : 1})}>{body}</Pressable>:<View style={{minHeight:80,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.borderSubtle}}>{body}</View>}
export function PinButton({item}:{item:QuickItem}){const data=useSuperAdminOperations();const pinned=data.pinned.some(value=>value.key===item.key);return <IconButton label={pinned?'Unpin item':'Pin item'} onPress={()=>data.togglePin(item)}><Ionicons name={pinned?'pin':'pin-outline'} size={sizing.iconMd} color={useRollCallTheme().colors.primary}/></IconButton>}
export function SavedFilters({scope,onApply,currentValue}:{scope:SavedFilter['scope'];onApply:(value:string)=>void;currentValue:string}){const data=useSuperAdminOperations();const filters=data.savedFilters.filter(item=>item.scope===scope);const[adding,setAdding]=useState(false);const[name,setName]=useState('');const[editing,setEditing]=useState<string>();return <RelationshipSection title="Saved filters"><View style={{paddingVertical:spacing.sm,gap:spacing.sm}}>{filters.map(filter=>editing===filter.id?<View key={filter.id} style={{gap:spacing.sm}}><TextField label="Filter name" value={name} onChangeText={setName}/><View style={{flexDirection:'row',gap:spacing.sm}}><Button label="Save name" disabled={!name.trim()} onPress={()=>{data.renameFilter(filter.id,name.trim());setEditing(undefined);}}/><Button label="Cancel" variant="text" onPress={()=>setEditing(undefined)}/></View></View>:<OperationalRow key={filter.id} title={filter.name} detail="Saved on this device" onPress={()=>onApply(filter.value)} status={filter.value}/>) }{adding?<View style={{gap:spacing.sm}}><TextField label="Filter name" value={name} onChangeText={setName}/><View style={{flexDirection:'row',gap:spacing.sm}}><Button label="Save filter" disabled={!name.trim()} onPress={()=>{data.saveFilter(scope,name.trim(),currentValue);setName('');setAdding(false);}}/><Button label="Cancel" variant="text" onPress={()=>setAdding(false)}/></View></View>:<Button label="Save current filter" variant="secondary" onPress={()=>{setName('');setAdding(true);}}/>}{filters.length?<View style={{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm}}>{filters.map(filter=><View key={filter.id} style={{flexDirection:'row'}}><Button label={`Rename ${filter.name}`} variant="text" onPress={()=>{setName(filter.name);setEditing(filter.id);}}/><Button label={`Remove ${filter.name}`} variant="text" onPress={()=>data.removeFilter(filter.id)}/></View>)}</View>:null}</View></RelationshipSection>}
export function LastUpdatedText({value}:{value:string}){const{colors}=useRollCallTheme();return <Text style={[typography.caption,{color:colors.textMuted}]}>Last updated {new Date(value).toLocaleString()}</Text>}
