import React, { createContext, useState } from 'react';

export type ApplicationStatus='New'|'Under Review'|'Contacted'|'Changes Requested'|'Approved for Payment'|'Payment Pending'|'Rejected'|'Paid'|'Workspace Active';
export type BillingCycle='Monthly'|'Yearly';
export type CollegeApplication={id:string;collegeName:string;officialEmail:string;phone:string;address:string;website:string;affiliation:string;institutionType:string;contactName:string;designation:string;contactEmail:string;contactPhone:string;plan:string;billingCycle:BillingCycle;capacity:number;appliedAt:string;status:ApplicationStatus;notes:string};
export type WorkspaceStatus='Pending'|'Active'|'Suspended'|'Payment Issue'|'Cancelled';
export type CollegeWorkspace={id:string;name:string;workspaceReference:string;address:string;university:string;contact:string;website:string;admin:string;plan:string;billingCycle:BillingCycle;amount:number;renewalDate:string;createdAt:string;status:WorkspaceStatus;setupStatus:string};
export type PaymentStatus='Paid'|'Due Soon'|'Failed'|'Overdue'|'Cancelled';
export type Subscription={id:string;collegeId:string;college:string;plan:string;billingCycle:BillingCycle;amount:number;tax:number;paymentDate:string;nextDueDate:string;reference:string;invoice:string;status:PaymentStatus;startDate:string;history:{date:string;amount:number;status:PaymentStatus;reference:string}[];planChanges:string[]};
export type Plan={id:string;name:string;description:string;price:number;billingCycle:BillingCycle;capacity:number;features:string[];status:'Active'|'Disabled'};
export type PlatformEvent={id:string;title:string;detail:string;at:string;destination:string};

const applicationsSeed:CollegeApplication[]=[
 {id:'app-abc',collegeName:'ABC Engineering College',officialEmail:'office@abc.edu',phone:'+91 80 4123 9000',address:'Outer Ring Road, Bengaluru, Karnataka',website:'https://abc.edu',affiliation:'Visvesvaraya Technological University',institutionType:'Autonomous engineering college',contactName:'Dr. Meera Iyer',designation:'Principal',contactEmail:'meera.iyer@abc.edu',contactPhone:'+91 98450 10001',plan:'Professional',billingCycle:'Monthly',capacity:2400,appliedAt:'2026-09-22T09:30:00.000Z',status:'Under Review',notes:'Accreditation documents reviewed.'},
 {id:'app-summit',collegeName:'Summit Institute of Technology',officialEmail:'office@summit.edu',phone:'+91 22 4100 2200',address:'Knowledge Park, Pune, Maharashtra',website:'https://summit.edu',affiliation:'Savitribai Phule Pune University',institutionType:'Private engineering college',contactName:'Anil Deshmukh',designation:'Registrar',contactEmail:'anil@summit.edu',contactPhone:'+91 98220 11002',plan:'Professional Annual',billingCycle:'Yearly',capacity:4100,appliedAt:'2026-09-23T11:15:00.000Z',status:'New',notes:''},
 {id:'app-riverdale',collegeName:'Riverdale College',officialEmail:'admin@riverdale.edu',phone:'+91 44 4200 3300',address:'University Avenue, Chennai, Tamil Nadu',website:'https://riverdale.edu',affiliation:'Anna University',institutionType:'Affiliated college',contactName:'Lakshmi Raman',designation:'Director',contactEmail:'lakshmi@riverdale.edu',contactPhone:'+91 98840 22003',plan:'Starter',billingCycle:'Monthly',capacity:900,appliedAt:'2026-09-18T08:00:00.000Z',status:'Approved for Payment',notes:'Approved for the requested capacity.'},
];
const collegesSeed:CollegeWorkspace[]=[
 {id:'college-development',name:'Development College',workspaceReference:'RC-DEV-001',address:'12 University Road, Bengaluru',university:'VTU',contact:'admin@development.local',website:'https://development.local',admin:'Development College Admin',plan:'Professional',billingCycle:'Monthly',amount:4999,renewalDate:'2026-10-15',createdAt:'2026-05-18',status:'Active',setupStatus:'Complete'},
 {id:'college-northstar',name:'Northstar Institute of Technology',workspaceReference:'RC-NIT-204',address:'Innovation Road, Hyderabad',university:'JNTUH',contact:'admin@northstar.edu',website:'https://northstar.edu',admin:'S. Krishnan',plan:'Professional Annual',billingCycle:'Yearly',amount:49999,renewalDate:'2027-09-21',createdAt:'2026-09-21',status:'Active',setupStatus:'In progress'},
 {id:'college-lakeside',name:'Lakeside College of Engineering',workspaceReference:'RC-LCE-188',address:'Lake View Campus, Mysuru',university:'VTU',contact:'admin@lakeside.edu',website:'https://lakeside.edu',admin:'Priya Rao',plan:'Starter',billingCycle:'Monthly',amount:2999,renewalDate:'2026-09-28',createdAt:'2026-04-12',status:'Payment Issue',setupStatus:'Complete'},
];
const paymentsSeed:Subscription[]=collegesSeed.map((college,index)=>({id:`sub-${college.id}`,collegeId:college.id,college:college.name,plan:college.plan,billingCycle:college.billingCycle,amount:college.amount,tax:Math.round(college.amount*.18),paymentDate:index===2?'2026-08-28':'2026-09-15',nextDueDate:college.renewalDate,reference:`PAY-2026-${3100+index}`,invoice:`INV-2026-${2100+index}`,status:index===2?'Failed':index===1?'Paid':'Due Soon',startDate:college.createdAt,history:[{date:index===2?'2026-08-28':'2026-09-15',amount:college.amount,status:index===2?'Paid':'Paid',reference:`PAY-2026-${3000+index}`}],planChanges:index===1?['Starter → Professional Annual · 21 Sep 2026']:[]}));
const plansSeed:Plan[]=[{id:'starter',name:'Starter',description:'Core attendance operations for smaller institutions.',price:2999,billingCycle:'Monthly',capacity:1000,features:['Attendance workflows','Role-based access','Standard reports'],status:'Active'},{id:'professional',name:'Professional',description:'Full RollCall operations for growing colleges.',price:4999,billingCycle:'Monthly',capacity:5000,features:['Everything in Starter','Advanced management','Priority email support'],status:'Active'},{id:'professional-annual',name:'Professional Annual',description:'Professional access with annual billing.',price:49999,billingCycle:'Yearly',capacity:5000,features:['Professional features','Annual billing','Price protection for the term'],status:'Active'}];
const initialEvents:PlatformEvent[]=[{id:'evt-1',title:'Northstar workspace created',detail:'Professional Annual · Active',at:'2026-09-23T12:00:00.000Z',destination:'/super-admin/colleges/college-northstar'},{id:'evt-2',title:'ABC moved under review',detail:'Application review started',at:'2026-09-23T10:30:00.000Z',destination:'/super-admin/applications/app-abc'},{id:'evt-3',title:'Development College payment received',detail:'₹4,999 · September renewal',at:'2026-09-22T15:10:00.000Z',destination:'/super-admin/payments/sub-college-development'}];
const allowed:Record<ApplicationStatus,ApplicationStatus[]>={'New':['Under Review'],'Under Review':['Contacted','Changes Requested','Approved for Payment','Rejected'],'Contacted':['Approved for Payment','Changes Requested','Rejected'],'Changes Requested':['Under Review'],'Approved for Payment':['Payment Pending','Paid'],'Payment Pending':['Paid'],'Rejected':[],'Paid':['Workspace Active'],'Workspace Active':[]};
type Value={applications:CollegeApplication[];colleges:CollegeWorkspace[];subscriptions:Subscription[];plans:Plan[];events:PlatformEvent[];transition:(id:string,status:ApplicationStatus,note?:string)=>void;updateWorkspaceStatus:(id:string,status:WorkspaceStatus)=>void;savePlan:(plan:Omit<Plan,'id'> & {id?:string})=>void;togglePlan:(id:string)=>void;updateConfiguration:(value:PlatformConfiguration)=>void;configuration:PlatformConfiguration};
type PlatformConfiguration={platformName:string;supportEmail:string;defaultCurrency:string;emailSender:string;notificationsEnabled:boolean};
const Context=createContext<Value|null>(null);
export function SuperAdminProvider({children}:React.PropsWithChildren){const[applications,setApplications]=useState(applicationsSeed);const[colleges,setColleges]=useState(collegesSeed);const[subscriptions]=useState(paymentsSeed);const[plans,setPlans]=useState(plansSeed);const[events,setEvents]=useState(initialEvents);const[configuration,setConfiguration]=useState<PlatformConfiguration>({platformName:'RollCall',supportEmail:'support@rollcall.app',defaultCurrency:'INR',emailSender:'RollCall',notificationsEnabled:true});const transition=(id:string,status:ApplicationStatus,note?:string)=>{const item=applications.find(value=>value.id===id);if(!item)return;if(!allowed[item.status].includes(status))throw new Error(`Cannot move ${item.status} to ${status}.`);setApplications(current=>current.map(value=>value.id===id?{...value,status,notes:note?`${value.notes}${value.notes?'\n':''}${note}`:value.notes}:value));setEvents(value=>[{id:`evt-${Date.now()}`,title:`${item.collegeName} ${status.toLowerCase()}`,detail:'Application status updated',at:new Date().toISOString(),destination:`/super-admin/applications/${item.id}`},...value]);};const updateWorkspaceStatus=(id:string,status:WorkspaceStatus)=>{setColleges(current=>current.map(item=>item.id===id?{...item,status}:item));const item=colleges.find(value=>value.id===id);if(item)setEvents(value=>[{id:`evt-${Date.now()}`,title:`${item.name} ${status.toLowerCase()}`,detail:'Workspace status updated',at:new Date().toISOString(),destination:`/super-admin/colleges/${item.id}`},...value]);};const savePlan=(value:Omit<Plan,'id'>&{id?:string})=>setPlans(current=>value.id?current.map(item=>item.id===value.id?{...value,id:value.id!}:item):[...current,{...value,id:`plan-${Date.now()}`}]);const togglePlan=(id:string)=>setPlans(current=>current.map(item=>item.id===id?{...item,status:item.status==='Active'?'Disabled':'Active'}:item));return <Context value={{applications,colleges,subscriptions,plans,events,transition,updateWorkspaceStatus,savePlan,togglePlan,configuration,updateConfiguration:setConfiguration}}>{children}</Context>}
export function useSuperAdmin(){const value=React.use(Context);if(!value)throw new Error('useSuperAdmin must be used within SuperAdminProvider');return value;}
export const applicationTransitions=allowed;
