import React, { useState } from 'react';
import { Text, View } from 'react-native';
import { router, type Href } from 'expo-router';
import { useAuth } from '@/auth/auth-provider';
import { Badge, Button, Card } from '@/design-system/components/core';
import { AlertBanner } from '@/design-system/components/feedback';
import { SwitchField, TextField } from '@/design-system/components/forms';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme, type ThemePreference } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { ManagementHeader, ManagementRow, RelationshipSection } from '@/hod/management-components';
import { LastUpdated } from '@/hod/operations-components';
import { DetailRow, ProfileIdentity, SettingsRow, ThemeOption } from '@/hod/profile-components';
import { AdminShell, SectionHeading } from './components';
import { useAdmin } from './admin-provider';
import { useAdminProfile } from './profile-provider';

const go = (href: string) => router.push(href as Href);
export function AdminProfilePage() { const { session } = useAuth(); const { profile } = useAdminProfile(); const data = useAdmin(); const { colors } = useRollCallTheme(); return <AdminShell activeKey="account" title="Profile" subtitle="College Admin account"><PageContainer width="detail"><ProfileIdentity name={profile.displayName} designation="College Administrator" department={data.workspace.name} onEdit={() => go('/admin/profile/edit')} /><View style={{ gap: spacing.sm }}><SectionHeading title="Account identity" /><View style={{ borderTopWidth: 1, borderTopColor: colors.borderSubtle }}><DetailRow label="Workspace" value={data.workspace.name} /><DetailRow label="Role" value="College Admin" /><DetailRow label="Official email" value={session?.user.loginIdentifier ?? 'Not available'} /><DetailRow label="Phone" value={profile.phone || 'Not added'} last /></View></View><AlertBanner title="Management-only access" message="This account manages one college workspace. Teaching, attendance-taking, Class Teacher, other-workspace, and Super Admin actions are not available." tone="info" /></PageContainer></AdminShell>; }
export function AdminProfileEditPage() { const { profile, saveProfile } = useAdminProfile(); const [name, setName] = useState(profile.displayName); const [phone, setPhone] = useState(profile.phone); const [error, setError] = useState(''); const save = async () => { if (!name.trim()) { setError('Display name is required.'); return; } await saveProfile({ displayName: name, phone }); router.replace('/admin/profile?saved=1' as Href); }; return <AdminShell activeKey="account" title="Edit profile" subtitle="Personal account information" back backFallback="/admin/profile"><PageContainer width="compact">{error ? <AlertBanner title="Check profile" message={error} tone="error" /> : null}<Card><TextField label="Display name" required value={name} onChangeText={setName} /><TextField label="Phone" keyboardType="phone-pad" value={phone} onChangeText={setPhone} /><Button label="Save profile" onPress={() => void save()} /><Button label="Cancel" variant="text" onPress={() => router.back()} /></Card></PageContainer></AdminShell>; }
export function AdminSettingsPage() { const { preference } = useRollCallTheme(); const labels = { system: 'System', light: 'Light', dark: 'Dark' } as const; return <AdminShell activeKey="account" title="Settings" subtitle="Account preferences"><PageContainer width="compact"><SectionHeading title="Account" /><SettingsRow icon="person-outline" title="Profile" detail="View and edit your College Admin profile" onPress={() => go('/admin/profile')} /><SettingsRow icon="shield-checkmark-outline" title="Account & Security" detail="Review identity, sign-in methods, and sessions" onPress={() => go('/admin/settings/security')} last /><SectionHeading title="Preferences" /><SettingsRow icon="contrast-outline" title="Appearance" detail="Choose how RollCall looks on this device" value={labels[preference]} onPress={() => go('/admin/settings/appearance')} /><SettingsRow icon="notifications-outline" title="Notification Preferences" detail="Choose account update preferences" onPress={() => go('/admin/settings/notifications')} last /><SectionHeading title="Support & information" /><SettingsRow icon="help-circle-outline" title="Help & Support" detail="Find answers or report a problem" onPress={() => go('/admin/settings/help')} /><SettingsRow icon="information-circle-outline" title="About RollCall" detail="App version, privacy, and product information" onPress={() => go('/admin/settings/about')} last /></PageContainer></AdminShell>; }
export function AdminAppearancePage() { const { preference, setPreference } = useRollCallTheme(); const select = (value: ThemePreference) => setPreference(value); return <AdminShell activeKey="account" title="Appearance" subtitle="Theme preference" back backFallback="/admin/settings"><PageContainer width="compact"><Text style={[typography.body, { color: useRollCallTheme().colors.textSecondary }]}>Your preference applies across RollCall on this device.</Text><View accessibilityRole="radiogroup"><ThemeOption value="system" selected={preference === 'system'} title="System" detail="Follow your device appearance" onSelect={select} /><ThemeOption value="light" selected={preference === 'light'} title="Light" detail="Always use the light theme" onSelect={select} /><ThemeOption value="dark" selected={preference === 'dark'} title="Dark" detail="Always use the near-black dark theme" onSelect={select} last /></View></PageContainer></AdminShell>; }
export function AdminSecurityPage() { const { session } = useAuth(); return <AdminShell activeKey="account" title="Account & Security" subtitle="Identity and sign-in" back backFallback="/admin/settings"><PageContainer width="compact"><RelationshipSection title="Account"><ManagementRow title="Sign-in information" detail={session?.user.loginIdentifier ?? 'Not available'} onPress={() => go('/admin/settings/security/information')} /><ManagementRow title="Sign-in methods" detail="Password and connected methods" onPress={() => go('/admin/settings/security/sign-in-methods')} /><ManagementRow title="Recovery" detail="Account recovery guidance" onPress={() => go('/admin/settings/security/recovery')} /></RelationshipSection><AlertBanner title="Workspace access" message="Your authenticated membership limits this account to one college workspace. Server-side enforcement remains the authority." tone="info" /></PageContainer></AdminShell>; }
export function AdminSecurityDetailPage({ kind }: { kind: 'information' | 'methods' | 'recovery' }) { const { session } = useAuth(); const title = kind === 'information' ? 'Sign-in Information' : kind === 'methods' ? 'Sign-in Methods' : 'Account Recovery'; const detail = kind === 'information' ? 'Review the identity used to access RollCall.' : kind === 'methods' ? 'Manage approved authentication methods without changing workspace access.' : 'Contact an authorized institutional administrator if account access is lost.'; return <AdminShell activeKey="account" title={title} subtitle="Account security" back backFallback="/admin/settings/security"><PageContainer width="compact"><ManagementHeader title={title} description={detail} /><Card>{kind === 'information' ? <><DetailRow label="Email" value={session?.user.loginIdentifier ?? 'Not available'} /><DetailRow label="Role" value="College Admin" last /></> : kind === 'methods' ? <><ManagementRow title="Password" detail="Enabled for this account" status="Active" /><ManagementRow title="Connected identity" detail="No additional provider connected" /></> : <><AlertBanner title="Recovery is institution-controlled" message="Use the official college support channel. RollCall will never ask for your password by email." tone="warning" /><Button label="Open Help & Support" onPress={() => go('/admin/settings/help')} /></>}</Card></PageContainer></AdminShell>; }
export function AdminNotificationSettingsPage() { const [account, setAccount] = useState(true); const [invitations, setInvitations] = useState(true); const [structure, setStructure] = useState(false); return <AdminShell activeKey="account" title="Notification Preferences" subtitle="Account updates" back backFallback="/admin/settings"><PageContainer width="compact"><AlertBanner title="C1 scope" message="These are personal account preferences only. College announcement management is not part of this build." tone="info" /><RelationshipSection title="Preferences"><SwitchField label="Account security" detail="Important sign-in and security changes" value={account} onValueChange={setAccount} /><SwitchField label="Invitation updates" detail="Acceptance and expiry of invitations you manage" value={invitations} onValueChange={setInvitations} /><SwitchField label="Academic structure changes" detail="Changes to workspace setup relationships" value={structure} onValueChange={setStructure} /></RelationshipSection></PageContainer></AdminShell>; }
export function AdminHelpPage() { return <AdminShell activeKey="account" title="Help & Support" subtitle="College Admin help" back backFallback="/admin/settings"><PageContainer width="compact"><ManagementHeader title="How can we help?" description="Guidance for workspace, people, and academic management." /><RelationshipSection title="Support"><ManagementRow title="Workspace setup" detail="Departments, academic years, and relationships" /><ManagementRow title="People & invitations" detail="Account status and invitation guidance" /><ManagementRow title="Report a problem" detail="Contact institutional RollCall support" /></RelationshipSection></PageContainer></AdminShell>; }
export function AdminAboutPage() { return <AdminShell activeKey="account" title="About RollCall" subtitle="Product information" back backFallback="/admin/settings"><PageContainer width="compact"><ManagementHeader title="RollCall V1" description="College workspace management foundation" /><RelationshipSection title="Information"><ManagementRow title="Product" detail="RollCall attendance and academic workspace" /><ManagementRow title="Privacy" detail="Institution-controlled workspace data" /><ManagementRow title="Terms" detail="Use is governed by your institution" /><ManagementRow title="Face data" detail="Not available to College Admin in this management build" /></RelationshipSection><Text style={[typography.caption, { color: useRollCallTheme().colors.textMuted }]}>Version 1.0 · Build C1</Text></PageContainer></AdminShell>; }
export function AdminActivityPage() { const data = useAdmin(); const { colors } = useRollCallTheme(); return <AdminShell activeKey="account" title="Activity" subtitle="Recent account and management activity" back backFallback="/admin/profile"><PageContainer width="standard"><ManagementHeader title="Recent changes" description="A compact record of recent management actions, not a full audit system." /><RelationshipSection title="Workspace activity">{data.recentChanges.map((item) => <ManagementRow key={item.id} title={item.action} detail={item.entity} meta={new Date(item.timestamp).toLocaleString()} />)}</RelationshipSection><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}><Badge label="Current workspace only" tone="info" /><LastUpdated value={data.lastUpdated} /></View><Text style={[typography.caption, { color: colors.textMuted }]}>Security-sensitive audit records are managed by the backend and are not represented by this compact activity view.</Text></PageContainer></AdminShell>; }
