import React from 'react';
import { View } from 'react-native';
import { router, type Href } from 'expo-router';
import { Button, Card, Statistic } from '@/design-system/components/core';
import { AlertBanner } from '@/design-system/components/feedback';
import { spacing } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { LastUpdated } from '@/hod/operations-components';
import { ManagementHeader, ManagementRow, RelationshipSection, SummaryStrip } from '@/hod/management-components';
import { AdminShell } from './components';
import { useAdmin } from './admin-provider';
import { useAdminOperations } from './operations-provider';

const go = (href: string) => router.push(href as Href);

export function SubscriptionPage() { const data = useAdmin(); const { subscription, lastUpdated } = useAdminOperations(); const students = data.people.filter((item) => item.role === 'Student').length; return <AdminShell activeKey="workspace" title="Subscription" subtitle="Plan and workspace capacity" back><PageContainer width="detail"><ManagementHeader title={`${subscription.plan} plan`} description={`${subscription.cycle} billing · Renews ${subscription.renewalDate}`} /><SummaryStrip items={[{ value: subscription.status, label: 'Workspace status' }, { value: subscription.paymentStatus, label: 'Payment' }, { value: `${students}/${subscription.studentCapacity}`, label: 'Student usage' }]} /><RelationshipSection title="Plan management"><ManagementRow title="Billing" detail="Cycle, payment status, and invoice history" onPress={() => go('/admin/subscription/billing')} /><ManagementRow title="Usage and limits" detail="Students, lecturers, and department usage" onPress={() => go('/admin/subscription/usage')} /><ManagementRow title="Workspace status" detail="Read-only operational state" status={subscription.status} onPress={() => go('/admin/workspace/status')} /></RelationshipSection><AlertBanner title="Billing is read-only" message="No payment provider is connected in RollCall V1. Plan changes and payment actions are handled by the authorized service provider." tone="info" /><LastUpdated value={lastUpdated} /></PageContainer></AdminShell>; }

export function BillingPage() { const { subscription } = useAdminOperations(); return <AdminShell activeKey="workspace" title="Billing" subtitle="Subscription history" back backFallback="/admin/subscription"><PageContainer width="detail"><ManagementHeader title="Billing overview" description="Provider-supplied subscription information" /><RelationshipSection title="Current billing"><ManagementRow title="Plan" detail={subscription.plan} /><ManagementRow title="Billing cycle" detail={subscription.cycle} /><ManagementRow title="Payment status" detail={subscription.paymentStatus} status="Active" /><ManagementRow title="Next renewal" detail={subscription.renewalDate} /></RelationshipSection><RelationshipSection title="Billing history"><ManagementRow title="September 2026" detail="Professional monthly · Paid" meta="Invoice reference INV-RC-0926" status="Active" /><ManagementRow title="August 2026" detail="Professional monthly · Paid" meta="Invoice reference INV-RC-0826" status="Active" /></RelationshipSection><AlertBanner title="Payments are provider-managed" message="RollCall does not collect payment details in this workspace. There are no payment or cancellation controls here." tone="info" /></PageContainer></AdminShell>; }

function Meter({ label, value, limit }: { label: string; value: number; limit: number }) { const { colors } = useRollCallTheme(); return <Card style={{ flex: 1, minWidth: 180 }}><Statistic value={`${value}/${limit}`} label={label} /><View accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: limit, now: value }} style={{ height: 6, borderRadius: 999, overflow: 'hidden', backgroundColor: colors.surfaceSecondary }}><View style={{ width: `${Math.min(100, value / limit * 100)}%`, height: '100%', backgroundColor: colors.primary }} /></View></Card>; }
export function UsagePage() { const data = useAdmin(); const { subscription, lastUpdated } = useAdminOperations(); return <AdminShell activeKey="workspace" title="Usage & Limits" subtitle="Workspace capacity" back backFallback="/admin/subscription"><PageContainer width="full"><ManagementHeader title="Current usage" description="Capacity is counted only within this authenticated college workspace." /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }}><Meter label="Students" value={data.people.filter((item) => item.role === 'Student').length} limit={subscription.studentCapacity} /><Meter label="Lecturers" value={data.people.filter((item) => item.role === 'Lecturer').length} limit={100} /><Meter label="Departments" value={data.departments.length} limit={25} /></View><AlertBanner title="Healthy capacity" message="Current usage is within the Professional plan limits." tone="success" /><LastUpdated value={lastUpdated} /></PageContainer></AdminShell>; }

export function WorkspaceStatusPage() { const data = useAdmin(); const { subscription, lastUpdated } = useAdminOperations(); return <AdminShell activeKey="workspace" title="Workspace Status" subtitle="Operational access" back backFallback="/admin/subscription"><PageContainer width="detail"><ManagementHeader title={data.workspace.name} description="Authenticated college workspace boundary" /><RelationshipSection title="Status"><ManagementRow title="Workspace" detail={data.workspace.status} status={data.workspace.status} /><ManagementRow title="Subscription" detail={subscription.status} status={subscription.status} /><ManagementRow title="Payment" detail={subscription.paymentStatus} status="Active" /><ManagementRow title="Role boundary" detail="College Admin · Management and oversight only" /></RelationshipSection><AlertBanner title="Status is read-only" message="Suspension, cancellation, and cross-workspace controls belong to the authorized service administrator, not College Admin." tone="info" /><Button label="View subscription" variant="secondary" onPress={() => go('/admin/subscription')} /></PageContainer></AdminShell>; }
