import React, { useEffect, useState } from 'react';
import { Text, View } from 'react-native';
import { router, type Href } from 'expo-router';
import { Badge, Button, Card } from '@/design-system/components/core';
import { AlertBanner } from '@/design-system/components/feedback';
import { TextField } from '@/design-system/components/forms';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { ManagementHeader, ManagementRow, RelationshipSection, SummaryStrip } from '@/hod/management-components';
import { AttentionRow, CopyIdentifier, LastUpdated } from '@/hod/operations-components';
import { AdminShell } from './components';
import { useAdmin } from './admin-provider';
import { useAdminOperations } from './operations-provider';
import { useAuth } from '@/auth/auth-provider';
import { adminClient, type WorkspaceSetup } from './admin-client';

const go = (href: string) => router.push(href as Href);
function entityRoute(key: string) { const [type, id] = key.split(':'); return type === 'department' ? `/admin/departments/${id}` : type === 'subject' ? `/admin/subjects/${id}` : type === 'section' ? `/admin/classes/${id}` : type === 'person' ? `/admin/people/${id}` : type === 'report' ? id === 'reports' ? '/admin/reports' : `/admin/reports/${id}` : type === 'issue' ? `/admin/attendance/issues/${id}` : type === 'period' ? '/admin/academic-years' : '/admin'; }

export function AdminDashboardPage() {
  const { colors } = useRollCallTheme(); const {session}=useAuth(); const [serverSetup,setServerSetup]=useState<WorkspaceSetup>(); const data = useAdmin(); const operations = useAdminOperations(); const currentYear = data.academicYears.find((item) => item.current); const hods = data.people.filter((item) => item.role === 'HOD'); const lecturers = data.people.filter((item) => item.role === 'Lecturer'); const students = data.people.filter((item) => item.role === 'Student');
  useEffect(()=>{if(session?.token)void adminClient.setup(session.token).then(setServerSetup).catch(()=>undefined);},[session?.token]);
  const departmentsWithoutHod = data.departments.filter((item) => !item.hodId); const subjectsWithoutAssignment = data.subjects.filter((item) => !data.assignments.some((assignment) => assignment.subjectId === item.id && assignment.lecturerId)); const classesWithoutTeacher = data.sections.filter((item) => !item.classTeacherId); const classesWithoutSchedule = data.sections.filter((item) => !operations.schedules.some((schedule) => schedule.sectionId === item.id)); const studentsWithoutClass = students.filter((item) => !item.sectionId); const pending = data.invitations.filter((item) => item.status === 'Pending'); const pendingAttendance = operations.sessions.filter((item) => item.state === 'Pending'); const unresolvedIssues = operations.issues.filter((item) => ['Submitted','Under Review'].includes(item.status)); const subscriptionWarnings = operations.subscription.status === 'Active' && operations.subscription.paymentStatus === 'Paid' ? 0 : 1; const attention = departmentsWithoutHod.length + subjectsWithoutAssignment.length + classesWithoutTeacher.length + classesWithoutSchedule.length + studentsWithoutClass.length + pending.length + pendingAttendance.length + unresolvedIssues.length + subscriptionWarnings;
  const operationalAttention = pendingAttendance.length + unresolvedIssues.length; const quick = [['Attendance','/admin/attendance'],['Schedule','/admin/schedule'],['Reports','/admin/reports'],['Monitoring','/admin/monitoring'],['Create notification','/admin/notifications/new'],['Subscription','/admin/subscription']] as const; const importantNotification = operations.notifications.find((item) => item.priority === 'High');
  return <AdminShell activeKey="dashboard" title="College Admin" subtitle="Workspace management"><PageContainer width="full">
    <ManagementHeader title={data.workspace.name} description={`${data.workspace.reference} · ${currentYear?.name ?? 'Academic year not set'}`} action="Workspace profile" onAction={() => go('/admin/workspace')} />
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing.md }}><Text accessibilityRole="header" style={[typography.heading, { color: colors.textPrimary }]}>College health</Text><Badge label={attention ? 'Attention' : 'Good'} tone={attention ? 'warning' : 'success'} /><Text style={[typography.bodySmall, { color: colors.textSecondary }]}>{attention ? `${attention} setup ${attention === 1 ? 'item needs' : 'items need'} review.` : 'The management foundation is complete.'}</Text></View>
    <SummaryStrip items={[{ value: data.departments.length, label: 'Departments' }, { value: hods.length, label: 'HODs' }, { value: lecturers.length, label: 'Lecturers' }, { value: students.length, label: 'Students' }, { value: data.sections.length, label: 'Classes' }, { value: data.subjects.length, label: 'Subjects' }]} />
    {serverSetup?<RelationshipSection title={`Workspace setup · ${serverSetup.completed}/${serverSetup.total}`}><View style={{gap:spacing.sm}}>{serverSetup.items.map((item)=><ManagementRow key={item.key} title={item.label} detail={item.complete?'Complete':item.count?`${item.count} configured`:'Not started'} status={item.complete?'Active':'Pending'}/>)}</View></RelationshipSection>:null}
    <RelationshipSection title="College operations"><ManagementRow title="Today's class completion" detail={`${operations.sessions.filter((item) => item.state === 'Conducted').length}/${operations.sessions.length} sessions conducted`} meta={`${operations.sessions.filter((item) => item.state === 'Pending').length} pending · ${operations.sessions.filter((item) => item.state === 'Not Conducted').length} not conducted`} status={operationalAttention ? 'Pending' : 'Active'} onPress={() => go('/admin/today-completion')} /><ManagementRow title="Attendance issues" detail={`${operations.issues.filter((item) => ['Submitted','Under Review'].includes(item.status)).length} requests need review`} status={operations.issues.some((item) => ['Submitted','Under Review'].includes(item.status)) ? 'Pending' : 'Active'} onPress={() => go('/admin/attendance/issues')} /><ManagementRow title="College notifications" detail={`${operations.notifications.filter((item) => item.status === 'Draft').length} drafts · ${operations.notifications.filter((item) => item.status === 'Failed').length} failed`} status={operations.notifications.some((item) => item.status === 'Failed') ? 'Failed' : 'Active'} onPress={() => go('/admin/notifications')} /><ManagementRow title="Subscription" detail={`${operations.subscription.plan} · ${operations.subscription.paymentStatus} · Renews ${operations.subscription.renewalDate}`} status={operations.subscription.status} onPress={() => go('/admin/subscription')} /></RelationshipSection>
    <RelationshipSection title="Setup and operations checklist"><AttentionRow count={departmentsWithoutHod.length} title="departments without HOD" detail="Department leadership is incomplete" onPress={() => go('/admin/departments')} /><AttentionRow count={subjectsWithoutAssignment.length} title="subjects without lecturer" detail="Teaching coverage needs an HOD assignment" onPress={() => go('/admin/assignments')} /><AttentionRow count={classesWithoutTeacher.length} title="classes without Class Teacher" detail="Class responsibility is unassigned" onPress={() => go('/admin/classes')} /><AttentionRow count={classesWithoutSchedule.length} title="classes without schedule" detail="Scheduled subject coverage is incomplete" onPress={() => go('/admin/schedule/monitoring')} /><AttentionRow count={studentsWithoutClass.length} title="students missing class placement" detail="Roster placement is incomplete" onPress={() => go('/admin/students')} /><AttentionRow count={pendingAttendance.length} title="pending attendance sessions" detail="Attendance processes are incomplete" onPress={() => go('/admin/attendance/monitoring')} /><AttentionRow count={unresolvedIssues.length} title="unresolved attendance issues" detail="Correction requests need review" onPress={() => go('/admin/attendance/issues')} /><AttentionRow count={pending.length} title="pending invitations" detail="Accounts are awaiting acceptance" onPress={() => go('/admin/invitations')} /><AttentionRow count={subscriptionWarnings} title="subscription warnings" detail="Plan or payment status needs attention" onPress={() => go('/admin/subscription')} /></RelationshipSection>
    {importantNotification ? <AlertBanner title={importantNotification.title} message={`${importantNotification.status} · ${importantNotification.audience} · ${importantNotification.message}`} tone={importantNotification.status === 'Failed' ? 'error' : 'info'} /> : null}
    <RelationshipSection title="Quick actions"><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }}>{quick.map(([label, href]) => <Button key={href} label={label} variant="secondary" onPress={() => go(href)} />)}</View></RelationshipSection>
    {data.pinned.length ? <RelationshipSection title="Pinned">{data.pinned.map((key) => <ManagementRow key={key} title={key.split(':')[1]?.replaceAll('-', ' ') ?? key} detail="Pinned workspace item" onPress={() => go(entityRoute(key))} />)}</RelationshipSection> : null}
    {data.recentlyViewed.length ? <RelationshipSection title="Recently viewed">{data.recentlyViewed.map((key) => <ManagementRow key={key} title={key.split(':')[1]?.replaceAll('-', ' ') ?? key} detail="Recently opened in this workspace" onPress={() => go(entityRoute(key))} />)}</RelationshipSection> : null}
    <RelationshipSection title="Recent changes">{operations.notifications.slice(0, 2).map((item) => <ManagementRow key={item.id} title={`Notification ${item.status.toLowerCase()}`} detail={item.title} meta={new Date(item.createdAt).toLocaleString()} />)}{operations.issues.filter((item) => item.decidedAt).slice(0, 1).map((item) => <ManagementRow key={item.id} title="Attendance issue resolved" detail={item.issueType} meta={new Date(item.decidedAt!).toLocaleString()} />)}{data.recentChanges.slice(0, 5).map((item) => <ManagementRow key={item.id} title={item.action} detail={item.entity} meta={new Date(item.timestamp).toLocaleString()} />)}</RelationshipSection>
    <View style={{ gap: spacing.xs }}><Text style={[typography.bodySmall, { color: colors.textSecondary }]}>Workspace status: <Text style={{ color: operations.subscription.status === 'Active' ? colors.success : colors.warning }}>{operations.subscription.status}</Text></Text><LastUpdated value={operations.lastUpdated > data.lastUpdated ? operations.lastUpdated : data.lastUpdated} /></View>
  </PageContainer></AdminShell>;
}

export function WorkspacePage({ edit = false }: { edit?: boolean }) {
  const data = useAdmin(); const { colors } = useRollCallTheme(); const [draft, setDraft] = useState(data.workspace); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const changed = JSON.stringify(draft) !== JSON.stringify(data.workspace);
  const save = () => { if (!draft.name.trim() || !draft.officialEmail.includes('@') || !draft.address.trim()) { setError('College name, valid official email, and address are required.'); return; } data.updateWorkspace(draft); setSaved(true); setError(''); router.replace('/admin/workspace?saved=1' as Href); };
  return <AdminShell activeKey="workspace" title={edit ? 'Edit workspace' : 'College workspace'} subtitle="Institution identity" back={edit} backFallback="/admin/workspace"><PageContainer width="detail">
    {saved ? <AlertBanner title="Workspace saved" message="Institution information is up to date." tone="success" /> : null}{error ? <AlertBanner title="Check workspace information" message={error} tone="error" /> : null}
    <ManagementHeader title={data.workspace.name} description="Approved institutional information for this college workspace" action={edit ? undefined : 'Edit'} onAction={() => go('/admin/workspace/edit')} />
    {edit ? <Card><TextField label="College name" required value={draft.name} onChangeText={(name) => setDraft({ ...draft, name })} /><TextField label="Official email" required keyboardType="email-address" autoCapitalize="none" value={draft.officialEmail} onChangeText={(officialEmail) => setDraft({ ...draft, officialEmail })} /><TextField label="Phone" keyboardType="phone-pad" value={draft.phone} onChangeText={(phone) => setDraft({ ...draft, phone })} /><TextField label="Address" required multiline value={draft.address} onChangeText={(address) => setDraft({ ...draft, address })} /><TextField label="Website" autoCapitalize="none" value={draft.website} onChangeText={(website) => setDraft({ ...draft, website })} /><TextField label="University / affiliation" value={draft.affiliation} onChangeText={(affiliation) => setDraft({ ...draft, affiliation })} /><TextField label="Institution type" value={draft.institutionType} onChangeText={(institutionType) => setDraft({ ...draft, institutionType })} /><View style={{ flexDirection: 'row', justifyContent: 'flex-end', flexWrap: 'wrap', gap: spacing.sm }}><Button label="Cancel" variant="text" onPress={() => changed ? setDraft(data.workspace) : router.back()} /><Button label="Save workspace" disabled={!changed} onPress={save} /></View></Card> : <>
      <View style={{ width: 72, height: 72, alignItems: 'center', justifyContent: 'center', borderRadius: 18, backgroundColor: colors.surfaceSecondary }}><Text style={[typography.title, { color: colors.primary }]}>{data.workspace.name.split(' ').slice(0, 2).map((part) => part[0]).join('')}</Text></View>
      <RelationshipSection title="Workspace identity"><ManagementRow title="Official email" detail={data.workspace.officialEmail} /><ManagementRow title="Phone" detail={data.workspace.phone} /><ManagementRow title="Address" detail={data.workspace.address} /><ManagementRow title="Website" detail={data.workspace.website} /><ManagementRow title="University / affiliation" detail={data.workspace.affiliation} /><ManagementRow title="Institution type" detail={data.workspace.institutionType} /><View style={{ paddingVertical: spacing.md }}><Text style={[typography.caption, { color: colors.textMuted }]}>Workspace reference</Text><CopyIdentifier label="workspace reference" value={data.workspace.reference} /></View></RelationshipSection>
    </>}
  </PageContainer></AdminShell>;
}

export function AcademicHubPage() { const data = useAdmin(); const current = data.academicYears.find((item) => item.current); return <AdminShell activeKey="academic" title="Academic Structure" subtitle={current?.name ?? 'No current academic year'}><PageContainer width="standard"><ManagementHeader title="Academic structure" description="Manage connected periods, departments, subjects, and classes." /><RelationshipSection title="Structure"><ManagementRow title="Academic Years" detail={`${data.academicYears.length} periods · ${current?.name ?? 'No current year'}`} onPress={() => go('/admin/academic-years')} /><ManagementRow title="Semesters" detail={`${data.semesters.length} semester contexts`} onPress={() => go('/admin/semesters')} /><ManagementRow title="Batches" detail={`${data.batches.length} department batches`} onPress={() => go('/admin/batches')} /><ManagementRow title="Departments" detail={`${data.departments.length} college departments`} onPress={() => go('/admin/departments')} /><ManagementRow title="Subjects" detail={`${data.subjects.length} subjects`} onPress={() => go('/admin/subjects')} /><ManagementRow title="Classes / Sections" detail={`${data.sections.length} classes`} onPress={() => go('/admin/classes')} /></RelationshipSection><LastUpdated value={data.lastUpdated} /></PageContainer></AdminShell>; }

export function AssignmentsPage() { const data = useAdmin(); const { colors } = useRollCallTheme(); return <AdminShell activeKey="invitations" title="Assignments Overview" subtitle="College-wide academic relationships"><PageContainer width="full"><ManagementHeader title="Assignment relationships" description="Inspection-only overview. Detailed assignment management remains with each HOD." />{data.assignments.map((assignment) => { const subject = data.subjects.find((item) => item.id === assignment.subjectId); const section = data.sections.find((item) => item.id === assignment.sectionId); const department = data.departments.find((item) => item.id === subject?.departmentId); const semester = data.semesters.find((item) => item.id === subject?.semesterId); const lecturer = data.people.find((item) => item.id === assignment.lecturerId); const teacher = data.people.find((item) => item.id === section?.classTeacherId); return <Card key={assignment.id}><View style={{ gap: spacing.xs }}><Text accessibilityRole="header" style={[typography.heading, { color: colors.textPrimary }]}>{subject?.name}</Text><Text style={[typography.bodySmall, { color: colors.textSecondary }]}>{department?.code} → {semester?.name} → {section?.name}</Text></View><ManagementRow title="Lecturer" detail={lecturer?.name ?? 'Unassigned'} status={lecturer ? 'Assigned' : 'Unassigned'} /><ManagementRow title="Class Teacher" detail={teacher?.name ?? 'Unassigned'} status={teacher ? 'Assigned' : 'Unassigned'} /></Card>; })}</PageContainer></AdminShell>; }
