import { Text, View } from 'react-native';
import { router, useLocalSearchParams, type Href } from 'expo-router';
import { useAuth } from '@/auth/auth-provider';
import { Badge, Button, Statistic } from '@/design-system/components/core';
import { spacing, typography } from '@/design-system/tokens';
import { useRollCallTheme } from '@/design-system/theme-provider';
import { PageContainer } from '@/shell/app-shell';
import { LecturerShell, ResourceState, SectionHeading } from '@/lecturer/components';
import { lecturerClient } from '@/lecturer/lecturer-client';
import { useResource } from '@/lecturer/use-resource';
export default function ClassDetails(){const {colors}=useRollCallTheme();const {classId}=useLocalSearchParams<{classId:string}>();const {session}=useAuth();const token=session?.token??'';const resource=useResource(()=>lecturerClient.classDetails(token,classId),[token,classId]);const item=resource.data;return <LecturerShell activeKey="classes" title={item?.subjectCode??'Class details'} subtitle={item?.batchName} back><PageContainer width="detail"><ResourceState loading={resource.loading} error={resource.error} retry={resource.retry}/>{item?<><View style={{gap:spacing.sm}}><Text accessibilityRole="header" style={[typography.title,{color:colors.textPrimary}]}>{item.subjectName}</Text><Text style={[typography.body,{color:colors.textSecondary}]}>{item.batchName} · {item.semester}</Text><Badge label={item.requiresAttendance?'Attendance due':'On schedule'} tone={item.requiresAttendance?'warning':'success'}/></View><View style={{flexDirection:'row',gap:spacing.giant,flexWrap:'wrap'}}><Statistic value={String(item.studentCount)} label="Students"/><Statistic value={String(item.completedSessions)} label="Sessions"/></View><View style={{paddingVertical:spacing.lg,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.borderSubtle,gap:spacing.md}}><SectionHeading title="Class information"/><Text style={[typography.body,{color:colors.textPrimary}]}>{item.schedule}</Text><Text style={[typography.bodySmall,{color:colors.textSecondary}]}>Lecturer · {item.lecturer?.name}</Text></View><View style={{gap:spacing.md}}><Button label="Start attendance" onPress={()=>router.push(`/lecturer/classes/${classId}/attendance` as Href)}/><Button label="View student roster" variant="secondary" onPress={()=>router.push(`/lecturer/classes/${classId}/students` as Href)}/></View></>:null}</PageContainer></LecturerShell>}
